### ISSUE TITLE
how do I purchase iap with different google account?

### ISSUE THREAD

**Issue by dreasn** [serso/android-checkout#100]
how do I purchase iap with different google account?
I've tried to change the account in PlayStore but in my app it still refer to first account.

At least the user can choose which account to make the in-app-purchase

**Comment by serso** [comment]
Billing API doesn't know about users and doesn't provide any API to choose a specific user account in the system. Please refer to https://stackoverflow.com/questions/15263889/does-in-app-billing-support-multiple-accounts and https://issuetracker.google.com/issues/36967788
