### ISSUE TITLE
Getting a second conflict & am not entirely sure how to fix it without only using 23.1.1

### ISSUE THREAD

**Issue by mrbradleyjh** [serso/android-checkout#101]
Error:Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (25.0.1) and test app (23.1.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by serso** [comment]
You can solve it by excluding the conflicting dependency. See https://github.com/serso/android-checkout#getting-started for example
