### ISSUE TITLE
 the error is "You already own this item".

### ISSUE THREAD

**Issue by Luckflower** [serso/android-checkout#103]
Google play pop-up error after the purchase is complete， the error is "You already own this item".
and below info in PurchaseListener:
onError---response = 7
onError---exception = com.cjl.game.billing.checkout.BillingException, 

Can you solve this problem ? thanks
![screenshot_20170714-145534](https://user-images.githubusercontent.com/8667539/28207615-ed88664c-68bc-11e7-9780-76fb8d2ce541.png)

**Comment by agaDeonix** [comment]
Hi, after success pay you need call consume for purchase.
Example 
fun consume(purchase: Purchase) {
        mCheckout.whenReady(object : Checkout.EmptyListener() {

            override fun onReady(requests: BillingRequests) {
                requests.consume(purchase.token, makeRequestListener());
            }
        })
    }

    fun makeRequestListener(): RequestListener<Any> {
        return object : RequestListener<Any> {
            override fun onSuccess(result: Any) {
                reloadInventory()
            }

            override fun onError(response: Int, e: Exception) {
                reloadInventory()
            }
        }
    }
private fun reloadInventory() {
        val request = Inventory.Request.create();
        // load purchase info
        request.loadAllPurchases();
        // load SKU details
        request.loadSkus(ProductTypes.IN_APP, getSkus())
        mCheckout.loadInventory(request, object : Inventory.Callback {
            override fun onLoaded(products: Inventory.Products) {
                mProducts = products
            }
        })
    }
Sorry for kotlin code

**Comment by serso** [comment]
@agaDeonix is right. If you want to purchase an item again - it should be consumed first. Please refer to the official Android billing documentation.
