### ISSUE TITLE
How to retrieve items (products and subscription) details

### ISSUE THREAD

**Issue by i-schuetz** [serso/android-checkout#105]
Hi,

I'm a bit confused about how to retrieve products details (e.g title, price and so on).

Using the IabHelper from "trivial drive" this can be done using `queryInventoryAsync(final boolean querySkuDetails, final List<String> moreItemSkus,
                                    final List<String> moreSubsSkus, final QueryInventoryFinishedListener listener)`

Here after digging in the source, I found there's `GetSkuDetailsRequest`, and looking at the test, it's used like this:

```java
final IInAppBillingService service = mock(IInAppBillingService.class);
final GetSkuDetailsRequest request = new GetSkuDetailsRequest("test", skus);
final RequestListenerSpy l = new RequestListenerSpy();
request.setListener(l);
//...
request.start(service, "");
```

I also found it in `Billing.java`, where it's as part of `getSkus` method:

```java
public int getSkus(@Nonnull String product, @Nonnull List<String> skus, @Nonnull RequestListener<Skus> listener) {
    Check.isNotEmpty(product);
    Check.isNotEmpty(skus);
    return runWhenConnected(new GetSkuDetailsRequest(product, skus), wrapListener(listener), mTag);
}
```

But this returns only skus.

What is the correct way to get the details?

Also, how do I get the details for both products and subscriptions - do I need to call the request twice?

**Comment by i-schuetz** [comment]
Ok, nevermind, I see that the type `Sku` contains all this data (I associate `Sku` more with an identifier...). The remaining question is if it is possible to retrieve products and subscriptions together?

**Comment by serso** [comment]
@i-schuetz, yes, you should call `#loadSkus` for each product in the app (in_app and subs) to get all the skus.
