### ISSUE TITLE
Error response: ERROR in GetSkuDetailsRequest(product_id) request

### ISSUE THREAD

**Issue by coderdaudat** [serso/android-checkout#109]
First of all: thanks for your hard work on this awesome library.
I'm facing with the problem:
I test buy consumer in android 4.4 it work like charm. But I test android 6.0 on Xiaomi Note4x device. I'v got a issue:  
Error response: ERROR in GetSkuDetailsRequest(inapp_add_fund) request
Removing pending request: GetSkuDetailsRequest(inapp_add_fund)

My code:

public class AddFundFrag extends BaseFragment implements
        View.OnClickListener,
        AddFundAdapter.OnItemPurchaseClickListener,
        UiCheckout.DestroyCheckoutListener{

    public static AddFundFrag getInstance() {
        return new AddFundFrag();
    }

    private static final List<String> SKUS = Arrays.asList("add_fund");
    
    private ActivityCheckout mCheckout;

    private UiCheckout mUiCheckout;
    @Nullable
    private Purchase mPurchase;

    private AddFundAdapter mAddFundAdapter;

    private final List<Inventory.Callback> mInventoryCallbacks = new ArrayList<>();

    private double mBalanceAdd = 0;

    private boolean isApprovalBuy = true;

    private Inventory.Request mRequest;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        final Billing billing = MyApplication.get(getActivity()).getBilling();
        mUiCheckout = Checkout.forUi(new MyIntentStarter(this), this, billing);
        mUiCheckout.start();
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);

    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_add_fund, container, false);

        RecyclerView recyclerView = (RecyclerView) view.findViewById(R.id.recycler_view);
        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(getContext());
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.addItemDecoration(new DividerSpacingItemDecoration(getContext(), R.dimen.item_number_space));

        view.findViewById(R.id.button_purchase_add_fund).setOnClickListener(this);

        mAddFundAdapter = new AddFundAdapter(getContext(), new ArrayList<SkuItem>(), this);
        recyclerView.setAdapter(mAddFundAdapter);

        mInventoryCallbacks.add(mAddFundAdapter);
		
        final Billing billing = MyApplication.get(getActivity()).getBilling();
        mCheckout = Checkout.forActivity(getActivity(), billing);
        mCheckout.start();
        reloadInventory();

        return view;
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.button_purchase_add_fund:
                break;
            default:
                break;
        }
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
//        mUiCheckout.loadInventory(Inventory.Request.create().loadAllPurchases(), new InventoryCallback());
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        mUiCheckout.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }

    @Override
    public void onDestroy() {
        mUiCheckout.stop();
        super.onDestroy();
    }

    @Override
    public void onItemClick(SkuItem skuItem) {
        if (isApprovalBuy) {
            mUiCheckout.loadInventory(Inventory.Request.create().loadAllPurchases(), new InventoryCallback(skuItem.getSku()));
            mUiCheckout.setDestroyCheckoutListener(this);
            isApprovalBuy = !isApprovalBuy;
        }
    }

    public double getBalance() {
        return mBalanceAdd;
    }

    private void reloadInventory() {
        mRequest = Inventory.Request.create();
        mRequest.loadPurchases(IN_APP);
        mRequest.loadSkus(IN_APP, SKUS);
        mCheckout.loadInventory(mRequest, new Inventory.Callback() {
            @Override
            public void onLoaded(@Nonnull Inventory.Products products) {
                for (Inventory.Callback callback : mInventoryCallbacks) {
                    callback.onLoaded(products);
                }
            }

        });
    }

    private class ConsumeListener extends EmptyRequestListener<Object> {

        private Sku mSku;

        public ConsumeListener(Sku sku) {
            mSku = sku;
        }

        @Override
        public void onSuccess(@Nonnull Object result) {
            mPurchase = null;
            purchase(mSku);
           
        }
    }

    private class PurchaseListener extends EmptyRequestListener<Purchase> {

        @Override
        public void onSuccess(@Nonnull final Purchase purchase) {
            mPurchase = purchase;

        }
    }

    private class InventoryCallback implements Inventory.Callback {

        private Sku mSku;

        public InventoryCallback(Sku sku) {
            mSku = sku;
        }

        @Override
        public void onLoaded(@Nonnull Inventory.Products products) {
            final Inventory.Product product = products.get(ProductTypes.IN_APP);
            DebugTool.logD("product: " + product.id);

            if (!product.supported) {
                return;
            }
            mPurchase = product.getPurchaseInState(mSku, Purchase.State.PURCHASED);

            purchase(mSku);

        }

    }

    private void purchase(final Sku sku) {
        if (mPurchase == null) {
            DebugTool.logD("PURCHASE NULL");
            mUiCheckout.startPurchaseFlow(sku, null, new PurchaseListener());
//            mUiCheckout.startPurchaseFlow(ProductTypes.IN_APP, skus, null, new PurchaseListener());
        } else {
          
            mUiCheckout.whenReady(new Checkout.EmptyListener() {
                @Override
                public void onReady(@Nonnull BillingRequests requests) {
                    requests.consume(mPurchase.token, new ConsumeListener(sku));
                }
            });
        }
    }

    /**
     * Trivial implementation of {@link IntentStarter} for the support lib's {@link Fragment}.
     */
    private static class MyIntentStarter implements IntentStarter {
        @Nonnull
        private final Fragment mFragment;

        public MyIntentStarter(@Nonnull Fragment fragment) {
            mFragment = fragment;
        }

        @Override
        public void startForResult(@Nonnull IntentSender intentSender, int requestCode, @Nonnull Intent intent) throws IntentSender.SendIntentException {
            mFragment.startIntentSenderForResult(intentSender, requestCode, intent, 0, 0, 0, null);
        }
    }

}

**Comment by serso** [comment]
@coderdaudat have you resolved the issue? Could you try running the sample app on the Xiaomi device?
