### ISSUE TITLE
Question / Needed Feature: How can I avoid checkout restart in this specific scenario?

### ISSUE THREAD

**Issue by rpattabi** [serso/android-checkout#111]
## Scenario
1. No internet connection on the device
1. Checkout is started through activity onCreate()
1. While the activity is loaded, I enable wifi through notification panel.
1. I come back to activity, request checkout to reload inventory

## Problem
The inventory is not reloaded fully. Checkout is still unaware of any skus or purchases.

## Reason
When activity is launched first without internet. INAPP and SUBSCRIPTION products are created with a state that billing is not support for either of these products. This state is never updated until start() is called again. 

There is a check when loading inventory to load skus (and purchases) only if billing is supported. So, even though when the internet connection is available and billing is now supported, checkout simply relies on this flag and still thinks that skus and purchases cannot be loaded.

## Workaround
When internet connection is enabled, I had to get the broadcast using a receiver and tell checkout to stop and start again so that it realizes that the billing is supported now.

## Solution
Clearly, the workaround is inefficient. It would be better if the library is written in such a way that it understands that the billing support state can change after checkout is started (or during the lifetime the activity).

OR @serso please let me know if I am missing something here that this restart can be avoided in the scenario I have presented.

**Comment by serso** [comment]
Valid concern. Another workaround is to disable the library's cache. I'll think about a proper fix in the meanwhile

**Comment by serso** [comment]
@rpattabi I have checked this scenario and it seems that Billing API has its own offline cache and it works fine even with no internet connection. In particular:
1. If I clean app's data and start it with no internet connection the Billing API returns `billing_is_supported=true`
2. If I try to load a list of SKUs with no internet connection then either I get an empty list from the Billing API if it's never been requested before or a list filled with data. In case of former the data can be cached in the library for some time (20 minutes for purchases and 1 day for SKU details)

Given that it seems that the scenario described by you should be supported. Can you please debug it a bit more and figure out why the Billing API returns `billing_is_supported=false` in your case?

**Comment by rpattabi** [comment]
Sorry, missed seeing your request. When I filed this issue, I saw why `billing_is_supported` became `false`. This is how it is:

In order to simulate first run of the app, I deleted app data **and** play store data. I think, clearing play store data makes billing unavailable till we reopen the play store app and accept the terms and conditions pop up. This resulted in `Checkout::start()` to have `mRequests.isBillingSupported` to get `onError` callback and thus products were assumed to have no billing support.

Note, this may look like artificial scenario i.e. clearing play store data. However, users are using all kinds of cleaner apps to reclaim space since many run out of storage. Most cleaner apps seem to wipe out play store data and app data (not just cache) which helps with decent space savings. This way, every app could run into the reported scenario.

**Comment by serso** [comment]
Hey @rpattabi,
I've found the real cause of your problem and prepared a fix for it.
Unfortunately, it breaks the existing API of Checkout and I'm still a bit hesitant to integrate the change.
Meanwhile you can build Checkout lib from the task branch `dev/bug-111` and verify that the issue is resolved.

**Comment by rpattabi** [comment]
@serso I see what you are doing. It will be interesting to see if retrieving products every time performs well compared to earlier implementation. I understand Google Play also does caching, but when I used IabHelper I found it is still bit slow to get the products.

I will test your fix when I get a chance again (within few days) and update here.

**Comment by serso** [comment]
I don't think that there will be any difference performance-wise. The problem was only with the cached products in Checkout class and not with the general cache used in Billing. The main cache is still enabled and used in Billing so isBillingSupported and getPurchases for example shouldn't take much time is they are in the cache
