### ISSUE TITLE
Crash: CheckoutInventory$Worker.countDown can't be negative

### ISSUE THREAD

**Issue by rpattabi** [serso/android-checkout#112]
I got a crash (on a Nougat device if it matters). This happened when I returned to an activity that uses checkout from another activity that doesn't use checkout. This is the stack trace:

```
Exception org.solovyev.android.checkout.Check$AssertionException: Can't be negative
org.solovyev.android.checkout.Check.isTrue (Check.java:98)
org.solovyev.android.checkout.CheckoutInventory$Worker.countDown (CheckoutInventory.java:90)
org.solovyev.android.checkout.CheckoutInventory$Worker.countDown (CheckoutInventory.java:84)
org.solovyev.android.checkout.CheckoutInventory$Worker.access$000 (CheckoutInventory.java:35)
org.solovyev.android.checkout.CheckoutInventory$Worker$1.onSuccess (CheckoutInventory.java:102)
org.solovyev.android.checkout.CheckoutInventory$Worker$1.onSuccess (CheckoutInventory.java:98)
org.solovyev.android.checkout.BaseInventory$SynchronizedRequestListener.onSuccess (BaseInventory.java:193)
org.solovyev.android.checkout.Billing$Requests$GetAllPurchasesListener.onSuccess (Billing.java:1151)
org.solovyev.android.checkout.Billing$Requests$GetAllPurchasesListener.onSuccess (Billing.java:1134)
org.solovyev.android.checkout.Billing$Requests$GetAllPurchasesListener.access$1602 (Billing.java:1134)
org.solovyev.android.checkout.MainThreadRequestListener$1.run (MainThreadRequestListener.java:55)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6123)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)
```

At the first look, it is unclear to me how I should prevent this issue. Any insights?

**Comment by serso** [comment]
I couldn't find anything in the source code neither could I reproduce the problem. Can you provide a code example and reproduction steps?

**Comment by rpattabi** [comment]
It is hard to reproduce. Definitely something to do with timing/race condition/etc. 

Upon looking at checkout code and my usage, I get this doubt: I am instantiating Requests only once and loading inventory using the same Requests instance for every resume of the activity. I suspect this could be the reason for the count to become negative. What do you think?

I will try out recreating Requests every time I call load inventory and let you know if I can reproduce the problem again.

**Comment by serso** [comment]
Reusing a `Request` instance shouldn't cause this crash as the counter is created for each `Inventory#load` call. What `Request` methods do you call prior to `Inventory#load`?

**Comment by rpattabi** [comment]
```
Inventory.Request.create()
                .loadAllPurchases()
                .loadSkus(ProductTypes.IN_APP, getInAppSkus())
                .loadSkus(ProductTypes.SUBSCRIPTION, getSubscriptionSkus());
```

**Comment by rpattabi** [comment]
And by the way, I don't have any subscription skus for the app that is experiencing this crash. This is from common code which I am trying to use for another app that has subscription skus.

**Comment by rpattabi** [comment]
I think this crash is due to the work around I did for #111. (As a rule, any work around comes back and bite you!) It is not consistently reproducible. But the following is the expected flow:

1. checkout is created and started
1. checkout restart i.e. stop and start again
1. checkout is stopped

If this flow happens repeatedly, at times, due to certain race condition, the reported crash happens. If I avoid restarting the checkout after stopping, I don't see the crash.
