### ISSUE TITLE
Promo Codes

### ISSUE THREAD

**Issue by sightshootkill** [serso/android-checkout#113]
Does Checkout support promo codes? When I check whether the product is purchased in InventoryCallback, I call isPurchased on the item when its been purchased with a promo code from a user and it returns false.

**Comment by rpattabi** [comment]
There should be no difference between promo and regular purchases as far as the application code / android checkout is concerned. There is one exception you should be aware of though:

**Google play does not provide developer payload for promo code purchases.**

So if you verify developer payload for purchase, it won't pass for purchases made using promo codes.

### What is Google's position on this?

Google is refusing to treat the missing developer payload as a bug in this case and they even started discouraging verification of developer payload (which they originally recommended to prevent cheating).

Why they can't simply provide the developer payload is just beyond my understanding.

**Comment by serso** [comment]
If what @rpattabi says is true then you can create your own PurchaseVerifier that can accept purchases done with promo codes.

**Comment by rpattabi** [comment]
Reference: https://github.com/googlesamples/android-play-billing/issues/7
