### ISSUE TITLE
Several fields missing from the Sku model, preventing full Subscription support

### ISSUE THREAD

**Issue by roughike** [serso/android-checkout#114]
According to [the official reference](https://developer.android.com/google/play/billing/billing_reference.html#getSkuDetails), the following are missing from the Sku model:

* introductoryPrice
* subscriptionPeriod
* freeTrialPeriod
* introductoryPricePeriod

@evil159 had to fork the library in order to have support for introductory prices in one of our customer projects. The fix is apparently in #108 .

I just created this issue so that the PR doesn't seem so random and go unnoticed.

Thanks for the nice library by the way! It was a lifesaver compared to the official one or the couple other popular libraries.

**Comment by serso** [comment]
I've merged the pull request

**Comment by roughike** [comment]
Thanks!
