### ISSUE TITLE
onError: 7 at RequestListener. product already owned

### ISSUE THREAD

**Issue by lheason** [serso/android-checkout#115]
are there any method in Billing/Checkout/Inventory to consume a product? I cannot perform a second transaction now =[

**Comment by serso** [comment]
`BillingRequests` class has `consume` method: https://github.com/serso/android-checkout/blob/e3857b16ee8bfec1a4acdc298f927170c336606a/lib/src/main/java/org/solovyev/android/checkout/BillingRequests.java#L244
