### ISSUE TITLE
startIntentSenderForResult gives error

### ISSUE THREAD

**Issue by adnbal89** [serso/android-checkout#116]
Hello,
I'm using your checkout library and doing purchase flow in my fragment. 

    `mCheckout = Checkout.forUi(new MyIntentStarter(this), this, billing);`

but, when I use : 
```
private static class MyIntentStarter implements IntentStarter {

    @Nonnull
    private final DialogFragment mFragment;

    public MyIntentStarter(@Nonnull DialogFragment fragment) {
      mFragment = fragment;
    }

    @Override
    public void startForResult(@Nonnull IntentSender intentSender, int requestCode,
        @Nonnull Intent intent) throws IntentSender.SendIntentException {
      mFragment.startIntentSenderForResult(intentSender, requestCode, intent, 0, 0, 0, null);
    }
  }
```

I got this error saying : 

**Call requires API level 24 (current min is 17): android.app.Fragment#startIntentSenderForResult**

I use min api 14.  And when I try to use my app on a phone android 4.4.2 , the code does'nt work really. for android 7.0 there is no problem. Could you give a solution or an alternative way, please ? Thank you.

**Comment by serso** [comment]
Have you read the documentation of [IntentSender](https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/IntentStarter.java)?
Here is an example of how to use Fragments from the support lib: https://github.com/serso/android-checkout/blob/667ce3c66de21c6a8fafeb300ce1b1e20e18f1c5/app/src/main/java/org/solovyev/android/checkout/app/BuyConsumeFragmentActivity.java#L155

**Comment by adnbal89** [comment]
oh,  I use android.app.Fragment  for my fragments, now I switched to support fragments and the warning goes away. thank you.
