### ISSUE TITLE
Ability to clear caches

### ISSUE THREAD

**Issue by RustamG** [serso/android-checkout#119]
Hi @serso!
First of all, thanks for your efforts. :)

I have a scenario in which I'd like to clear caches of all purchased products in the app when the user logs out in the app. Is it currently supported?

**Comment by serso** [comment]
@RustamG, you can use `Cache#clear()` method: https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Cache.java#L78
`Cache` can be accessed from `Configuration` object that you pass to `Billing`.

**Comment by pcegarra** [comment]
A method to get the configuration object could be great
