### ISSUE TITLE
Unable to Check Purchased SUBSCRIPTION

### ISSUE THREAD

**Issue by ahmedchoteri** [serso/android-checkout#120]
Unable to get the SUBSCRIPTION which is already purchased. Please help me i am using following code.

final Inventory.Product product = products.get(SUBSCRIPTION);
                for (Purchase purchase : product.getPurchases()) {
                    if (purchase.state != Purchase.State.PURCHASED) {
                        continue;
                    }
                    final Sku sku = product.getSku(purchase.sku);
                    if (sku != null) {
                        //purchased SUBSCRIPTION
                    }
                }

**Comment by serso** [comment]
`Purchase` object is all you need. If you want to load more information about a specific SKU (aka SKU details) you should use `Inventory.Request#loadSkus` method:
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Inventory.java#L324
