### ISSUE TITLE
Failed to verify purchased item

### ISSUE THREAD

**Issue by lheason** [serso/android-checkout#121]
Hi,

good work for the library. great effort on simplifying the in-app purchase journey
However, I was not able to verify the purchase made through the library, the data structure there is different from the google standard and i was not able to verify it using my own remote library

I grab the purchase result callback from .createPurchaseFlow the EmptyRequestListener, and pass the purchase result to my server, however the return object is not in the format of {data:xxx, signature:xxx} while in the data object there is no purchaseToken there

Anything i have done wrong??

**Comment by lheason** [comment]
FYI, this is what i got 
`{
  "productId": "xxxx",
  "orderId": "xxxxx",
  "packageName": "xxxx",
  "purchaseTime": 11111,
  "purchaseState": 0,
  "token": "xxxxx",
  "signature": "xxxxx"
}`

and from google it should look like
`{
    "data":{
      "packageName":"xxxxxx",
      "productId":"xxxxxx",
      "purchaseTime":111111,
      "purchaseState":0,
      "purchaseToken":"xxxxxx",
      "autoRenewing":true
    },
    "signature":"xxxxx"
  }`

**Comment by serso** [comment]
Try implementing PurchaseVerifier. See Billing.Configuration#getPurchaseVerifier for more details.

**Comment by lheason** [comment]
why do i have to implement the purchase verifier if i want to verify it at server? i want to verify it using a remote server integrating with some 3rd party in-app purchase logic

fyi, im trying to verify using this node.js project
http://iap.gracenode.org/#validate-android

 but there is no success =[

**Comment by serso** [comment]
Because it is designed exactly for that purpose, please check out its docs: https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/PurchaseVerifier.java

**Comment by lheason** [comment]
even if i have done implement the verification logic there, yet there is no success =[

how can i get the purchase callback object the same as the one suggested from google?

**Comment by serso** [comment]
You can use `Purchase#data` field to get the data sent by Google:
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchase.java#L71
