### ISSUE TITLE
Validate Purchases

### ISSUE THREAD

**Issue by tomrum** [serso/android-checkout#123]
Hello,

Thanks for the library but I don't understand how to validate purchases. I have been looking at https://github.com/serso/android-checkout/issues/12 it is rather confusing. I don't understand when things are written in a cryptic way such as ActivityCheckout#createPurchaseFlow(RequestListener<Purchase>

It is not obvious to me where to find these methods, how to override, where to override etc.

I know how to send json to my server and back. Please can you give some actual code to do the validation and where to put the code, which object etc and explain.

Thanks

**Comment by rpattabi** [comment]
When you instantiate Billing, you have opportunity to provide PurchaseVerifier.

```
new Billing(context, new Billing.DefaultConfiguration() {
            @Nonnull
            @Override
            public PurchaseVerifier getPurchaseVerifier() {
                // TODO: Instantiate PurchaseVerifier and override verify()
            }
```

**Comment by tomrum** [comment]
Thanks, could you give some more details. Which class does this code go? How do I do the // TODO: Instantiate PurchaseVerifier and override verify() ? And I assume when my backend returns a true or false verification, how does purchase verifier know that?

Thanks

**Comment by rpattabi** [comment]
The questions you are asking are the decisions you should make based on your app specifics. You should be able to figure it out yourself once you understand the roles and responsibilities of different components of this library. Start with [READ ME](https://github.com/serso/android-checkout/blob/master/README.md) and [this article](https://hackernoon.com/implementing-in-app-billing-in-android-4896232c7d6b).

**Comment by tomrum** [comment]
Sorry but I have read those links and I am not a genius, I would like some help. Can you provide me with a tiny bit more help please - I don't think it is obvious. Thanks

**Comment by tomrum** [comment]
Hello developers, the aim of this library is " Its main goal is to make integration of in-app products as simple and straightforward as possible: developers should not spend much time on implementing boring In-App Billing API but should focus on more important things - their apps"

I think the developer may be able to do more to explain how to use this library especially in regard to validating purchases. Not everyone will have hours and days to read the source and try to figure it out.

Can anyone help please?

**Comment by serso** [comment]
Here is a walk-through:
1. Implement a `PurchaseVerifier` interface preferably extending `BasePurchaseVerifier`, say `MyPurchaseVerifier`
2. In the code where you instantiate `Billing` class provide a `Billing.Configuration` instance whose `#getPurchaseVerifier` method returns a `MyPurchaseVerifier` object:
```
Billing mBilling = new Billing(context, new Billing.DefaultConfiguration() {
            @Nonnull
            @Override
            public PurchaseVerifier getPurchaseVerifier() {
                return new MyPurchaseVerifier();
            }
```

That's it. The library will call `PurchaseVerifier`'s callback when:
1. A new purchase is done
2. A list of existing purchases is loaded

**Comment by tomrum** [comment]
Thanks for this. I have set up PurchaseVerifier but when I make a test payment and log purchases to console I get:

[Purchase{state=PURCHASED, time=1508864157572, sku='test'}]

Do you know why there is no order id which is required for validation?

Thanks

**Comment by serso** [comment]
@tomrum `Purchase#toString` doesn't provide such information. Either use `Purchase#orderId`
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchase.java#L46
or raw json sent by Google
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchase.java#L71

**Comment by tomrum** [comment]
Thanks for your help. I have a problem with validating on the server when the server returns I try to call listener onSuccess but get this error:
org.solovyev.android.checkout.Check$AssertionException: Must be called on the same thread
 at org.solovyev.android.checkout.Check.equals(Check.java:93)
                                                                                   at org.solovyev.android.checkout.GetPurchasesRequest$VerificationListener.onSuccess

I am using Google networkFragment sample which I assume creates another background thread. How do I get back on the listener thread?

Cheers!

**Comment by serso** [comment]
There are two possibilities:
1. Either the listener thread is the main application thread and then you can use a `Handler` with the main looper (`Looper.getMainLooper`)
2. Or if the listener thread is a background thread you can safely block its execution while another "worker" thread is computing the result. As soon as the result is ready you can continue execution on the waiting thread. You might want to use `Future` or `CountDownLatch` classes to perform proper synchronization

**Comment by tomrum** [comment]
Thanks again, that helped.
Purchase verifier is called when products are loaded and also when a purchase is made. How can one differentiate the two?

Cheers!

**Comment by serso** [comment]
@tomrum there is no way to distinguish a new purchase from the old one in `PurchaseVerifier`. Why does it matter? The verification procedure shouldn't depend on it.

**Comment by tomrum** [comment]
O.k. When the user makes a purchase, PurchaseVerifier gets called and a request is sent to my server to validate. If their exists an entry in the database for order id already(because it has already been purchased) it should be rejected and the server returns false, then my code should not unlock feature. PurchaseVerifier also gets called when loading a screen of skus but should my server be returning false again as their is no way to distinguish a new purchase from the old one?

So when you call listener's onsuccess or onerror, what does this do? Are you supposed to call onsuccess for a newly validated purchase and onerror when it has already been purchased? And should you call either onsuccess or onerror for each purchase?

Thanks :-)

**Comment by serso** [comment]
Each purchase regardless of it being new or old should be verified. If you track purchases on a server than for each purchase the server should return `true` if it is valid and `false` if it is not. The reason for this is that both old and new purchases come to the app from a blackbox (aka billing API) which can be hacked. Thus, the server shouldn't know if a purchase is old or new, it should check its validity.
Please check out ["Security Best Practices"](https://developer.android.com/google/play/billing/billing_best_practices.html) on d.android.com.

As written in the doc:
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/PurchaseVerifier.java#L40
the listener should be passed a list of verified, i.e. valid, purchases. It might be empty if all the purchases are invalid.

**Comment by tomrum** [comment]
"the listener should be passed a list of verified, i.e. valid, purchases." by this do you mean the listeners onsuccess? Also when would onerror be called by my code?

**Comment by serso** [comment]
@tomrum yes, I'm talking about `#onSuccess` as only this method accepts a list of purchases. 
`#onError` might be called when an error occurs in your code, such as an unexpected exception. Empty list of purchases is not an error and thus `#onSuccess` should be called.

**Comment by tomrum** [comment]
I am sending a request to server for each item in purchases, is it o.k to call listener's onsuccess once for each verified purchase? (or do they have to be grouped as a list and onsuccess called once? Thanks again :-)

**Comment by serso** [comment]
@tomrum no. You have to wait while all purchases are validated.

**Comment by tomrum** [comment]
Hi, I know individual purchase can be converted to json but is there an easy way to bundle purchases into json object to transmit to server?

Thanks again! :-)

**Comment by serso** [comment]
@tomrum wouldn't `JSONArray` from SDK be enough?

**Comment by tomrum** [comment]
Sorry, I'm a bit stupid sometimes, where is JSONArray in SDK?

Thanks

**Comment by serso** [comment]
`org.json.JSONArray`

**Comment by tomrum** [comment]
Hello again, I have managed to implement purchase verifier now but it doesn't quite work. I am returning a list of validated purchases to the listener but my purchased features are not unlocking properly.

Is this correct, when somebody first makes a purchase the purchase is entered into the backend database and true is returned and that purchase is sent to the listener and then unlocks the app feature. The problem is the next time the user uses the app the purchase verifier is triggered and the purchase is sent to backend but because that order Id is already in the database the backend now returns false which means the feature doesn't get unlocked again when it should be unlocked. Am I doing something wrong here?

Thanks again! :-) :-)

**Comment by serso** [comment]
@tomrum https://github.com/serso/android-checkout/issues/123#issuecomment-340285124

**Comment by tomrum** [comment]
I have read these but I'm still confused, how is one supposed to unlock features each time someone uses the device when after the first purchase the server always returns false?

Thanks

**Comment by serso** [comment]
@tomrum you can change the server implementation.

**Comment by tomrum** [comment]
"Check the returned data signature and the orderId, and verify that the orderId is a unique value that you have not previously processed." this means that server has to return false the next time backend it is queried right? But then feature won't be unlocked.

**Comment by serso** [comment]
> "Check the returned data signature and the orderId, and verify that the orderId is a unique value that you have not previously processed."
Where does this come from?

**Comment by tomrum** [comment]
https://developer.android.com/google/play/billing/billing_best_practices.html#key

Validate on a server

num 2

**Comment by serso** [comment]
Then it's wrong. Purchases should be validated regardless of whether they are new or old. The brand new Trivial Drive does the same: https://github.com/googlesamples/android-play-billing/blob/3493967b5d7f54861efbfc1038d21d820077942b/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java#L253

So you can ask Google why their docs are wrong.

**Comment by tomrum** [comment]
So to clarify in respect to the order ID if this is already registered in the database then it should still return true assuming all other verifications have succeeded?

**Comment by serso** [comment]
@tomrum correct

**Comment by tomrum** [comment]
Thanks very much for your help! :-)
The signature is not coming through for each purchase in doVerify.
Cheers :-)

**Comment by serso** [comment]
@tomrum that sounds strange.

**Comment by tomrum** [comment]
productId, orderId,packageName,purchaseTime,purchaseState and token come through but no signiture. Any ideas?

Thanks

**Comment by serso** [comment]
@tomrum does it happen when a new item is purchased or when a list of existing purchases is loaded?
In case of the former you can put a breakpoint in https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/PurchaseFlow.java#L113,  in case of the latter - in https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchases.java#L95

**Comment by tomrum** [comment]
It happens in both instances

**Comment by serso** [comment]
@tomrum are you testing on a released version of the app?

**Comment by tomrum** [comment]
closed beta

**Comment by serso** [comment]
If the billing API doesn't sent a signature the library can't fix it, you need to figure out what causes it.
It might be a configuration/setup problem or an account problem. I can't help you with that.

**Comment by tomrum** [comment]
o.k thanks

**Comment by tomrum** [comment]
Whats the worst that can happen if I don't validate signiture? thanks

**Comment by tomrum** [comment]
I think it might be the public key:
Can you explain this: Encryption.decrypt(s, "se.solovyev@gmail.com"); from Billing

Thanks!

**Comment by serso** [comment]
@tomrum I used my email as a salt in encryption/decryption of the PK. You should use your own obfuscation algorithm. Please take a look at: https://developer.android.com/google/play/billing/billing_best_practices.html#validating-purchase-device

Not validating the signature equals no validation at all so it's something you shouldn't skip.

**Comment by tomrum** [comment]
I got the signiture to come through, I was calling toJson() rather than toJson(true).
The signiture is different for each purchase. I thought it would be the same - app icense key.
So can I ask: what is it and how to I validate it on backend?

Almost there! Thanks :-)

**Comment by tomrum** [comment]
Could you please confirm this, then hopefully i'll be finished and won't have to ask any more questions:

Am I right to think that the signiture is unique to each in-app product and stays the same reguardless of customer purchasing it?

Then validation will be easy,

Many thanks :-)

**Comment by serso** [comment]
@tomrum sorry for late response. Yes, signature should be unique

**Comment by tomrum** [comment]
Hi, I managed to figure it out and am now successfully validating the response json. Thanks for all your help, I really appreciate it :-)

**Comment by serso** [comment]
You are welcome!
