### ISSUE TITLE
Response code different from Google documentation

### ISSUE THREAD

**Issue by arrix** [serso/android-checkout#126]
While inspecting a purchase failure, I noticed an inconsitency in the response code definition.

There is     public static final int ACCOUNT_ERROR = 2; in
https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/ResponseCodes.java#L43
but according to https://developer.android.com/google/play/billing/billing_reference.html
2 should be BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE.

Other errors in ResponseCodes.java matches the documentation.

**Comment by serso** [comment]
@arrix thanks for noticing this, will fix in the next release
