### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by nburaktaban** [serso/android-checkout#129]
I am trying to use your library but i have some errors.

[Here ](https://gist.github.com/nburaktaban/dc1fe172e8b58df4e1b231b67d2e86b7)my gist:
https://gist.github.com/nburaktaban/dc1fe172e8b58df4e1b231b67d2e86b7

I also tried to late initialize 'mCheckout' and then I got an error in [this line](https://gist.github.com/nburaktaban/dc1fe172e8b58df4e1b231b67d2e86b7#file-storeactivity-java-L57).

Any suggestions?

**Comment by serso** [comment]
Use this instead of getApplicationContext when you create a Billing instance in BillingApplication
