### ISSUE TITLE
Error with the successfull payment

### ISSUE THREAD

**Issue by blood73** [serso/android-checkout#130]
Some of my app have the problem with in app. They received error with code 2 (BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE), but the money is withdrawn from the account. What I can do with this?

Here the code snippet:

`public class InappActivity extends BaseActivity {

    private static ActivityCheckout mCheckout;
    private InventoryCallback mInventoryCallback;
    private Purchase mPurchase1;

    private static final String MILEAGE_1 = "mileage_1";
    private static final int MILEAGE_1_PRICE = 49;
    private static final int USER_CANCEL_PURCHASE_CODE = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        /* ..... */

        final Billing billing = App.get(this).getBilling();
        mCheckout = Checkout.forActivity(this, billing);
        mCheckout.start();
        mInventoryCallback = new InventoryCallback();

        reloadInventory();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        mCheckout.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }

    private static List<String> getInAppSkus() {
        final List<String> skus = new ArrayList<>();
        skus.addAll(Arrays.asList(MILEAGE_1));
        return skus;
    }

    private void reloadInventory() {
        final Inventory.Request request = Inventory.Request.create();
        // load purchase info
        request.loadAllPurchases();
        // load SKU details
        request.loadSkus(ProductTypes.IN_APP, getInAppSkus());
        mCheckout.loadInventory(request, mInventoryCallback);
    }

    private void consume(final Purchase purchase) {
        mCheckout.whenReady(new Checkout.EmptyListener() {
            @Override
            public void onReady(@Nonnull BillingRequests requests) {
                requests.consume(purchase.token, makeRequestListener());
            }
        });
    }

    private <T> RequestListener<T> makeRequestListener() {
        return new RequestListener<T>() {
            @Override
            public void onSuccess(@Nonnull T result) {
            }

            @Override
            public void onError(int response, @Nonnull Exception e) {
            }
        };
    }

    private class PurchaseListener extends EmptyRequestListener<Purchase> {
        @Override
        public void onSuccess(@Nonnull Purchase purchase) {

            if (purchase.sku.equals(MILEAGE_1)) {
                increaseInAppCount(1);
                consume(purchase);
            }
        }

        @Override
        public void onError(int response, @Nonnull Exception e) {

            /* .....Here the ERROR CODE 2 */
        }
    }

    @OnClick(R.id.card_1)
    protected void onClickCard1() {

        if (mPurchase1 != null) {
            consume(mPurchase1);
        } else {
            try {
                mCheckout.startPurchaseFlow(ProductTypes.IN_APP, MILEAGE_1,
                        null, new InappActivity.PurchaseListener());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void updateInventory(Inventory.Product product) {
        Sku mileage1InApp = product.getSku(MILEAGE_1);

        int price1 = MILEAGE_1_PRICE;

        if (mileage1InApp != null) {
            try {
                price1 = Integer.parseInt(RegexUtil.extractFirstNumber(mileage1InApp.price));
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }
        }
        

        initPrices(price1);
    }

    private class InventoryCallback implements Inventory.Callback {

        public InventoryCallback() {}

        @Override
        public void onLoaded(@Nonnull Inventory.Products products) {
            final Inventory.Product product = products.get(ProductTypes.IN_APP);
            if (!product.supported) {
                // billing is not supported, user can't purchase anything
                return;
            }

            mPurchase1 = product.getPurchaseInState(MILEAGE_1, Purchase.State.PURCHASED);

            updateInventory(product);
        }
    }

    private void updateMileageCount() {
        HistoryDatabaseHelper databaseHelper = HistoryDatabaseHelper.getInstance(InappActivity.this);
        int mileageNumber = databaseHelper.getMileageCount();
    }

    private void increaseInAppCount(int count) {
        HistoryDatabaseHelper databaseHelper = HistoryDatabaseHelper.getInstance(InappActivity.this);
        databaseHelper.increaseMileageCount(count);
        updateMileageCount();
    }

    private void initPrices(int price1) {

        /* PRICE 1 */
        String price1String = MileageInappActivity.this.getResources().getString(R.string.price, price1);
        price1Text.setText(price1String);
        /* /PRICE 1 */
    }
}`

**Comment by hughpearse** [comment]
Bump
I am seeing this too.
I am using org.solovyev.android:checkout:1.2.1 so that my application can use targetSdkVersion 23. This allows it to support devices starting from android v6.

When I purchase a product (sucessfully):
DonateActivity: Button5 was pressed, mCheckout is ready
DonateActivity: Purchase failed.
DonateActivity: Response 10001
DonateActivity: Exception java.lang.IllegalArgumentException: org.solovyev.android.checkout.Base64DecoderException: Bad Base64 input character at 15: 44(decimal)

My project
https://github.com/hughpearse/androidtexttospeechereader/blob/master/app/src/main/java/hughpearse/myapplication004/DonateActivity.java
