### ISSUE TITLE
List of SKUs crash

### ISSUE THREAD

**Issue by tomrum** [serso/android-checkout#131]
Hello again, I'm wondering if you are aware of this crash:

On the list of SKUs if you tap a product twice before the purchase dialog has time to open, the app crashes (at least on Marshmallow).

Thanks!

**Comment by serso** [comment]
I assume it crashes because of the same request code used twice? If yes then there are two options:
1. Either you prevent clicking the same button until the purchase flow finishes
2. Or you start a new purchase flow with a new request code
