### ISSUE TITLE
Unable to validate purchase (product.isPurchased(...))

### ISSUE THREAD

**Issue by andoni90** [serso/android-checkout#133]
Hello,

I cannot get my app to verify that the purchase is done.

product.isPurchased(Constants.IN_APP_SKU_VERSION_PRO)

This line always returns false, tried with my own SKU and "android.test.purchased" as well.

Its really weird because if I evaluate it as an expression in debug mode it returns true, but running always returns false.

Tried to clean, rebuild, etc. and same result. Any ideas?

Thanks in advance.

**Comment by serso** [comment]
Do you see anything in the log? Do you test on a released version of the app?

**Comment by andoni90** [comment]
5696-5696/com.xxxxx W/zygote64: Verification of org.solovyev.android.checkout.Purchase org.solovyev.android.checkout.Inventory$Product.getPurchaseInState(java.lang.String, org.solovyev.android.checkout.Purchase$State) took 250.424ms

Testing in release version and debug. Same result.

**Comment by serso** [comment]
If you put a breakpoint in PurchaseVerifier do you get an empty list there?

**Comment by andoni90** [comment]
I think I did not set any PurchaseVerifier, should I set one?

**Comment by serso** [comment]
If you haven't set a PurchaseVerifier, https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/DefaultPurchaseVerifier.java is used. Put a breakpoint there and see if you get a list of purchases.

**Comment by andoni90** [comment]
Both "android.test.purchased" and my sku and processed and returned in DefaultPurchaseVerifier. Seems to work OK.

At the same time, I saw that this method is returning null all the time:

    @Nullable
    static Purchase getPurchaseInState(@Nonnull List<Purchase> purchases, @Nonnull String sku, @Nonnull Purchase.State state) {
        for (Purchase purchase : purchases) {
            if (purchase.sku.equals(sku)) {
                if (purchase.state == state) {
                    return purchase;
                }
            }
        }
        return null;
    }

This line:  "if (purchase.state == state) { " is returning false but both sku and state seems to be the same and if I evaluate the expression it returns true. 

Is it possible that is some kind of error related to cache? It is very weird.

**Comment by andoni90** [comment]
![purchases1](https://user-images.githubusercontent.com/33420387/34167337-caa3a50a-e4e1-11e7-8d45-6f6a507e8afa.png)
![purchases2](https://user-images.githubusercontent.com/33420387/34167338-cac0ba6e-e4e1-11e7-886e-f061815a3ec2.png)

**Comment by serso** [comment]
Debugger might sometimes show you a wrong line. If you step out from this method you should see what happens with a purchase next (looking at the screenshot I'm pretty sure a non-null value is returned)

**Comment by serso** [comment]
You can as well check other purchases in the list. It might be that the list contains the same purchase in cancelled state and it is "neutralized" in https://github.com/serso/android-checkout/blob/5b84d50a19a499ef0f44ab8e84001748f7bab90f/lib/src/main/java/org/solovyev/android/checkout/Purchases.java#L123

**Comment by andoni90** [comment]
The list looks OK, only two items, android.test.debug and my sku. Debugged in neutralize method and returns both purchases:

![1](https://user-images.githubusercontent.com/33420387/34168159-142866c8-e4e4-11e7-8185-c2016f85440c.png)
![2](https://user-images.githubusercontent.com/33420387/34168161-1440c8e4-e4e4-11e7-8cac-baf4fdb69dea.png)

**Comment by andoni90** [comment]
I think I found it.

Debug was fooling me all the time, as you said it was working ok but showing me wrong line. The error was in another part of my code. 

Thanks a lot and sorry for the waste of time.

**Comment by TheMaxCoder** [comment]
I have come across this problem multiple times now, where `product.isPurchased(SKU)` is always false no matter what I do. though purchase flow works alright.

For future reference for myself and anybody else having this issue please double check your Public Key Integration.
