### ISSUE TITLE
How to use promo codes as part of purchase flow?

### ISSUE THREAD

**Issue by DesigningKnights** [serso/android-checkout#136]
Ok I have seen in other apps allowing the entry of promo codes in the payment dialog.  At the point where you can insert a credit card it allows you to change payment methods to promo codes.  My question is how do I do that in this library?  When I get to the purchase flow for credit card payment, I'm only given credit card options and no options for redeeming codes.  Is there a way to do this?
![screenshot_20171230-163205](https://user-images.githubusercontent.com/8666549/34452654-49d4a360-ed7f-11e7-963c-08ae0357006d.png)

Notice the REDEEM option.  I never get that option in my app.  Is there something special I need to do to get that?  Note that I am using a different device to test, and not using a testing account.

**Comment by serso** [comment]
[Google billing doc](https://developer.android.com/google/play/billing/billing_promotions.html):
> You create promo codes through the Google Play Console. Each promo code is associated with a single product registered in the Play Console.

> A user can redeem a promo code in one of these two ways:

> The user can enter the promo code as part of the app's ordinary purchase flow, as described in Implementing In-app Billing. As far as the app is concerned, this is just like an ordinary purchase, except that the user makes a payment with a promo code instead of with money.
The user can redeem the code in the Google Play Store app. The user can type the code in the Google Play Store app manually, or you can generate a URL in your app that automatically provides the code in the Google Play Store for them.
