### ISSUE TITLE
Checkout.whenReady throws AssertionException

### ISSUE THREAD

**Issue by Marty** [serso/android-checkout#137]
Hi,
I'm getting a few of these errors from users:
```
org.solovyev.android.checkout.Check$AssertionException: 
  at org.solovyev.android.checkout.Check.isNotNull (Check.java:62)
  at org.solovyev.android.checkout.Check.isNotNull (Check.java:57)
  at org.solovyev.android.checkout.Checkout.whenReady (Checkout.java:224)
```
In my tests the library worked fine.
My implementation follows the instructions in this repo strictly (start, createPurchaseFlow, makeInventory, load etc.).

This is causing it:
```
private void buyPro() {
        checkout.whenReady(new Checkout.EmptyListener() {
            @Override
            public void onReady(BillingRequests requests) {
                requests.purchase(ProductTypes.IN_APP, PRO_SKU, null, checkout.getPurchaseFlow());
            }

            @Override
            public void onReady(@Nonnull BillingRequests requests, @Nonnull String product, boolean billingSupported) {
                ...
            }
        });
    }
```

Any idea what's causing this?
I think maybe unchecked exceptions are a bit too lax for this.

The android versions I got the reports from are 4.4, 5.1, 6.0, 7.0 with no specific device standing out.

**Comment by serso** [comment]
You can strip `Check` calls using Proguard: https://github.com/serso/android-checkout/blob/master/lib/proguard-rules.txt. However in this case it would crash a couple of lines below with NPE.

Is it possible that you call `Checkout#whenReady` after it has been stopped? Alternatively, you might check whether you call `Inventory` methods after `Checkout` has been stopped.

**Comment by Marty** [comment]
I don't think so.
The only place where I'm calling `Checkout.stop()` is the `onDestroy()` method of my activity.
And the method `buyPro` is only called via user input, so I'd doubt that somebody could click that button after the activity is destroyed.

**Comment by davidvavra** [comment]
I'm experiencing the same crash for some users. Various devices and OS versions.

`Fatal Exception: org.solovyev.android.checkout.Check$AssertionException: Object should not be null
       at org.solovyev.android.checkout.Check.isNotNull + 62(Check.java:62)
       at org.solovyev.android.checkout.Check.isNotNull + 57(Check.java:57)
       at org.solovyev.android.checkout.Checkout.whenReady + 224(Checkout.java:224)`

**Comment by hixfield** [comment]
Same here. Did somebody find something?
