### ISSUE TITLE
Better proguard setup

### ISSUE THREAD

**Issue by MFlisar** [serso/android-checkout#139]
Bacause of following proguard config

	-assumenosideeffects class org.solovyev.android.checkout.Check {
		static *;
	}

I get following warnings:

	Note: the configuration specifies that none of the methods of class 'org.solovyev.android.checkout.Check' have any side effects
	Note: the configuration specifies that none of the methods of class 'org.solovyev.android.checkout.Check' have any side effects
	Note: there were 2 '-assumenosideeffects' options that try to match all
		  methods with wildcards. This will likely cause problems with methods like
		  'wait()' and 'notify()'. You should specify the methods more precisely.
		  (http://proguard.sourceforge.net/manual/troubleshooting.html#nosideeffects)
		  
Could you explain which fields/functions we need to keep in order to have checkout work properly?

**Comment by MFlisar** [comment]
**Suggestion**

	-keep class com.android.vending.billing.**

	-assumenosideeffects class org.solovyev.android.checkout.Billing {
		public static void debug(...);
		public static void warning(...);
		public static void error(...);
	}

    # REMOVE THIS! This is potentially dangerous as it will strip away Object.wait/notify and similar as well
	#-assumenosideeffects class org.solovyev.android.checkout.Check {
	#    static *;
	#}

	-assumenosideeffects class org.solovyev.android.checkout.Check {
		static void isMainThread();
		static void isNotNull(...);
		static void notEquals(...);
		static void equals(...); 
		static void isTrue(...);
		static void isFalse(...);
		static void isNull(...);
		static void isNotEmpty(...);
		static void same(...);
	}

	-dontwarn javax.annotation.**

	-keepclassmembers enum * {
		public static **[] values();
		public static ** valueOf(java.lang.String);
	}

What do you think of this proguard file? It should work as well, shouldn't it?

**Comment by serso** [comment]
@MFlisar `Check` class is a replace of `assert` keyword so you most probably don't need it in production. Two warnings that you get are just warnings and using `assumenosideeffects` on a whole `Check` class shouldn't cause any issues.

**Comment by MFlisar** [comment]
I have read an answer to an issue from a proguard dev (I just can't find it anymore) where he explained why the wildcard is dangerous and explained this based on rmeoving log messages.

At least the manual here says following (https://www.guardsquare.com/en/proguard/manual/examples#logging):

> The wildcards are a shortcut to match all versions of the methods. Be careful not to use a * wildcard to match all methods, because it would also match methods like wait(), higher up the hierarchy. Removing those invocations will generally break your code.

The quote says, this wildcard effects code **higher up** the hierarchy, so I'm not sure if you're setup is safe. And in my use case I currently could solve my proguard issues with the above settings (fastly tested though yet)

**Comment by serso** [comment]
@MFlisar you can't remove code from SDK classes, so at least `Object#wait` and `Object#notify` will be there even after Proguard's `-assumenosideeffects class XXX {static *;}`. Additionally, `Check` is a very simple class that doesn't use multi-threading (where wait/notify are used) so I don't think it can break anything.

This might still be needed though but it's another issue:
```
-keepclassmembers enum * {
	public static **[] values();
	public static ** valueOf(java.lang.String);
}
```

**Comment by serso** [comment]
Okay, now I understood the issue, you're right @MFlisar. See e.g. https://stackoverflow.com/questions/16846691/proguard-ate-my-object-wait

**Comment by MFlisar** [comment]
Correct. That's what I meant and why I highlighted the "higher up the hierarchy" that's talked about in the documentation which I assume indicates this problem

**Comment by serso** [comment]
@MFlisar now when I've looked at this again I don't think it's an issue :)
The thing is that this rule matches only static methods, thus, it shouldn't affect `wait()` or `notify()`

**Comment by MFlisar** [comment]
I'm not sure why the wildcard is not limited to `class org.solovyev.android.checkout.Check` (which would make sense for me) so I'm not totally sure if the `static` word with the wildcard is working correctly...

Proguard at least prints the same info massage if you use `static *` as well...

**Comment by rpattabi** [comment]
Wondering about the conclusion for this issue. Should we worry about the proguard warning?
