### ISSUE TITLE
FallbackInventory - when is it used

### ISSUE THREAD

**Issue by MFlisar** [serso/android-checkout#140]
I think this should only be called on old phones with a old play store version that does not support billing v3 yet, correct?

I don't have problems at all, but one user with a HTC one M9 running lineageos 13.0.2 has problems and I see in the logs that the library is calling the fallback method...

Am I understanding the fallback false or do you have an explanation for this?

**Comment by serso** [comment]
https://github.com/serso/android-checkout/blob/caa84e16aa57bb70f917cef7e6a73d6fff1b8ce0/lib/src/main/java/org/solovyev/android/checkout/Billing.java#L697
Fallback inventory is only needed if you have used some other solution for billing v.2. It's very unlikely that you need it. Note that the default implementation returns `null`: https://github.com/serso/android-checkout/blob/caa84e16aa57bb70f917cef7e6a73d6fff1b8ce0/lib/src/main/java/org/solovyev/android/checkout/Billing.java#L737

**Comment by MFlisar** [comment]
I never used another billing library and never used the v2 version either... Weirdly, the user told me he bought my app on the same phone and now I see that `getFallbackInventory` is called...

**Comment by serso** [comment]
@MFlisar what exactly is called? `Configuration#getFallbackInventory` is called every time the lib is initialized but by default it returns null and nothing happens. Do you have any issue (crash/ANR?) caused by this method?

**Comment by MFlisar** [comment]
You are totally right, it's called every time. I just did not remember to have seen this message already and thought based on it's name it could be the reason for my problem.

I have one user where the in app purchase seems to not work anymore, although following is true:

* same phone
* one google account only
* active internet connection

Still I get reported that 0 products are loaded and non is purchased... But it's not this reason, this was a logical misunderstanding from my side
