### ISSUE TITLE
Need help with check if product is purchased

### ISSUE THREAD

**Issue by jackaru** [serso/android-checkout#141]
I'm a newbie with listeners and callbacks so I don't know where to start to check if a product is purchased or not.
I need to check it to show the "Purchase" button if a product isn't purchased yet, and I also need to be able to check it offline.
Is it possible? Can i get an example? Thanks in advance!

**Comment by serso** [comment]
Please refer to [README](https://github.com/serso/android-checkout/blob/master/README.md).
If you prefer digging the sources - there is a sample project: https://github.com/serso/android-checkout/tree/master/app.
There is also a step-by-step tutorial on Medium if you prefer this format: https://medium.com/@se.solovyev/implementing-in-app-billing-in-android-4896232c7d6b
