### ISSUE TITLE
Question : Support for android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by NukeGeneral** [serso/android-checkout#144]
Is it possible to add checkout support for support versions of Fragment?

**Comment by serso** [comment]
Please take a look here https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/IntentStarter.java
and here https://github.com/serso/android-checkout/blob/5bc98d8590f2a82593b7b581d46ebc19497eaa42/app/src/main/java/org/solovyev/android/checkout/app/BuyConsumeFragmentActivity.java#L155

**Comment by NukeGeneral** [comment]
Oh sorry,my bad. I was expecting same method like Checkout.fromFragment(//support version here) . Thanks for your help.
