### ISSUE TITLE
Active Subscription

### ISSUE THREAD

**Issue by yothin** [serso/android-checkout#145]
How to check subscription is active?

`mCheckout.loadInventory(request, new Inventory.Callback() {
            @Override
            public void onLoaded(@Nonnull Inventory.Products products) {

                for(Inventory.Product product : products){

                    for (Purchase purchase : product.getPurchases()) {
                        if (purchase.state != Purchase.State.PURCHASED) {
                            continue;
                        }
                        final Sku sku = product.getSku(purchase.sku);
                        if (sku != null && purchase.autoRenewing) {
                            //purchased SUBSCRIPTION is active
                            //unlock content here
                        }
                    }
                }

            }
        });`
This is correct?

Thanks

**Comment by serso** [comment]
It looks fine but for this code to work you need to load SKU information as well.
Also, notice that subscriptions might not be "auto-renewing". You filter out such subscriptions with this code
