### ISSUE TITLE
ITEM_ALREADY_OWNED, but Inventory fetch returns nothing

### ISSUE THREAD

**Issue by willswinson** [serso/android-checkout#146]
Hey there,

I was testing my IAP by buying and consuming products in my app when suddenly I got into a state that will always return a response code 7 of ITEM_ALREADY_OWNED even though there are no purchases returned to me when loading my inventory. It was working fine until this happened and now I'm completely stuck in this state and have no clue to get around it, as I cannot consume the purchase since I can't load it.

This is how I am fetching my purchases:

```
val checkout = Checkout.forApplication(App.instance.billing)
checkout.start()
val inv = checkout.makeInventory()

val p = inv.load(
                Inventory.Request.create().
                        loadAllPurchases().
                        loadSkus(ProductTypes.IN_APP, listOf(
                                Instrument.productIDForThing(0),
                                Instrument.productIDForThing(1),
                                Instrument.productIDForThing(2),
                                Instrument.productIDForThing(3),
                                Instrument.productIDForThing(4),
                                Instrument.productIDForThing(5)
                        )), Inventory.Callback { products ->

            Handler(Looper.getMainLooper()).post {
                for (product in products) {
                    for (purchase in product.purchases) {
                        checkout.whenReady(object : Checkout.Listener {
                            override fun onReady(requests: BillingRequests) {
                                requests.consume(purchase.token, object : RequestListener<Any> {
```

I've tried "adb shell pm clear com.android.vending" in terminal and restarting the device. Nothing can get it out of this state.

**Comment by serso** [comment]
`Product` contains purchases in different states. You should only be interested in purchases in state `Purchased`.

**Comment by willswinson** [comment]
Thanks for responding.  I haven't changed the code from when it was working before. I was making purchases, and they would appear in product.purchases here.

 Is there a different method call or something?  I figured this would get each purchase in every state. Then I could iterate and get the ones with state "Purchased".

But product.purchases is always empty no matter what I do.

**Comment by serso** [comment]
The code generally looks good so it must be something else that caused the issue. Do you test on a published version of the app?

**Comment by willswinson** [comment]
Ya I'm testing on an alpha build uploaded to Google Play.  The only thing I can think of doing is make a new Gmail to test with, which is definitely not ideal.

Maybe it isn't android-checkout, because I found this here, and the guy never posted a solution:

https://stackoverflow.com/questions/15542687/iabhelper-queryinventoryasync-returns-no-purchases-yet-launch-product-flow-fai

**Comment by willswinson** [comment]
You can close this. I have no clue what happened.
