### ISSUE TITLE
Base64 decoding failed.

### ISSUE THREAD

**Issue by savurajkumar** [serso/android-checkout#147]
Base64 decoding failed.
04-02 14:59:19.179 14567-14567/? W/System.err: java.lang.IllegalArgumentException: org.solovyev.android.checkout.Base64DecoderException: Bad Base64 input character at 0: 93(decimal)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Security.generatePublicKey(Security.java:85)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Security.verifyPurchase(Security.java:62)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.DefaultPurchaseVerifier.verify(DefaultPurchaseVerifier.java:48)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.PurchaseFlow.onActivityResult(PurchaseFlow.java:115)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.ActivityCheckout.onActivityResult(ActivityCheckout.java:263)
04-02 14:59:19.180 14567-14567/? W/System.err:     at spendeye.com.spendeye.home.SubscriptionsActivity.onActivityResult(SubscriptionsActivity.java:205)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:7128)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:4142)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4189)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.os.Looper.loop(Looper.java:163)
04-02 14:59:19.180 14567-14567/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6205)
04-02 14:59:19.180 14567-14567/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-02 14:59:19.180 14567-14567/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
04-02 14:59:19.180 14567-14567/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
04-02 14:59:19.180 14567-14567/? W/System.err: Caused by: org.solovyev.android.checkout.Base64DecoderException: Bad Base64 input character at 0: 93(decimal)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Base64.decode(Base64.java:543)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Base64.decode(Base64.java:471)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Base64.decode(Base64.java:419)
04-02 14:59:19.180 14567-14567/? W/System.err:     at org.solovyev.android.checkout.Security.generatePublicKey(Security.java:75)
04-02 14:59:19.180 14567-14567/? W/System.err: 	... 16 more

**Comment by serso** [comment]
You supply a public key in non-base64 format. Please check `Configuration#getPublicKey` implementation.

**Comment by savurajkumar** [comment]
Where can i find **Configuration#getPublicKey**

**Comment by serso** [comment]
https://github.com/serso/android-checkout#example

**Comment by savurajkumar** [comment]
Yes I have used  **return Encryption.decrypt(s, "se.solovyev@gmail.com");** still it is giving same error.

**Comment by serso** [comment]
@savurajkumar just return your public key to test if it works (no encryption needed)
