### ISSUE TITLE
Subscription was canceled but still arrive as purchased

### ISSUE THREAD

**Issue by ihorvlasyuk** [serso/android-checkout#150]
Subscription was canceled in google play but still arrive as purchased

**Comment by serso** [comment]
Some time is needed for synchronization to be done. You can as well disable caches in the library.

**Comment by pcegarra** [comment]
Is there a method to clean the cache ?

**Comment by ghataa** [comment]
same here

**Comment by ghataa** [comment]
It works fine if I manually clear the play store cache. Maybe something is wrong with the play store app cache mechanism?

**Comment by pcegarra** [comment]
I had to validate on the server if the purchase is still valid

**Comment by ghataa** [comment]
This works fine after waiting 2 days :) I tested with test subscriptions, maybe this works faster with real subs. But this issue is definitely because of the play store app!

**Comment by ihorvlasyuk** [comment]
I have also tested with test subscriptions. Hope that with real subscriptions everything will be ok. But still have worries.

**Comment by SammyO** [comment]
I'm experiencing the same issue. We also use a server to validate if the subscription is still valid, as the library seems to return state `PURCHASED` for cancelled and expired subscriptions.

**Comment by serso** [comment]
The library uses data provided by Google Play app. If it provides wrong/invalid data there is nothing the library can do.
