### ISSUE TITLE
EmptyRequestListener implementation onSuccess/onError never called

### ISSUE THREAD

**Issue by ascendedco** [serso/android-checkout#151]
### Problem
When making a subscription purchase using checkout, the EmptyRequestListener implementation's onSuccess and onError functions never get called.
### Setup
The account I'm testing with is listed as a test user, as described [here.](https://developer.android.com/google/play/billing/billing_testing#test-purchases-sandbox) This might be the problem, but I haven't got around to testing it.

All the items are subscriptions, not products.

### Request Listener Implementation
A very simple override, that just calls the success function passed in as a parameter as soon as a purchase succeeds.
```kotlin

class PurchaseListener(val success: () -> Unit): EmptyRequestListener<Purchase>() {

    override fun onSuccess(result: Purchase) {
        Log.e(tag(), "[Billing] Success")
        success()
        super.onSuccess(result)
    }

    override fun onError(response: Int, e: Exception) {
        Log.e(tag(), "[Billing] Error ${e.localizedMessage}")
        super.onError(response, e)
    }
}
```

### Billing Service
Wraps some checkout logic to minimize activity code.
```kotlin
class BillingService(private val activity: Activity, private val success: () -> Unit) {

    private val checkout = Checkout.forActivity(activity, MyApp.billing)

    fun start() {
        checkout.start()
        checkout.createPurchaseFlow(PurchaseListener(success))
        // Load list of subscriptions.
        checkout.makeInventory().load(Inventory.Request.create()
                .loadAllPurchases()
                .loadSkus(ProductTypes.SUBSCRIPTION, listOf(
                    "sub01", "sub02", "sub03", "sub04", "sub05"
                )),
                Inventory.Callback {
                    // Log all received subscriptions.
                    it.forEach { product ->
                        Log.e(tag(), "[Billing] Product Type ${product.id}")
                        product.skus.forEach { sku ->
                            Log.e(tag(), "[Billing] Title ${sku.displayTitle}")
                            Log.e(tag(), "[Billing] Description ${sku.description}")
                        }
                    }
                })
    }

    fun stop() {
        checkout.stop()
    }

    // Trigger a purchase for the given sku.
    fun purchase(sku: String) {
        checkout.whenReady(object: Checkout.EmptyListener() {
            override fun onReady(requests: BillingRequests) {
                requests.purchase(ProductTypes.SUBSCRIPTION, sku, null, checkout.purchaseFlow)
            }
        })
    }
}
```
### Activity Code
How the service is implemented in the activity.
```kotlin
private var billing: BillingService

override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_purchase)

        billing = BillingService(this) {
            // Fires when billing succeeds. See BillingService class.
            // This never gets called.
        }
        billing.start()
}
```
The purchase flow is started in an onClickListener as follows:
```kotlin
billing.purchase("sub01")
```

**Comment by ascendedco** [comment]
@serso

**Comment by MajorFriend** [comment]
I had the same problem and managed to fix it, but I don't rember how exactly.... 

I just followed the README.md tutorial (your code looks fine btw), uploaded a closed Alpha test and made a testers list. The day after it was deployed, then you need to activate your tester account with the link provided in the play console. Once it's done, the app will be available on the play store and the purchase flow works perfectly.

Try the above steps, I remember the onSuccess and onError functions were never called at the beginning, but after deploying the alpha etc (no need to download the app, you just need to have the same app version than the uploaded one), the onError function were called everytime saying the product is unavailable.

I don't think it's a Checkout issue but I'm not an Android Billing pro, it's the first time I implement it.

Good luck

**Comment by ascendedco** [comment]
@MajorFriend I decided to implement the Google Play Billing library independently. As it turns out, this library (Checkout) is a thin wrapper around the Google Play Billing library, and doesn't really decrease complexity. 

IMO it's easier to just use Google's API directly.
