### ISSUE TITLE
ITEM_ALREADY_OWNED, but Inventory fetch returns empty

### ISSUE THREAD

**Issue by blood73** [serso/android-checkout#154]
Please help with this issue.

Consumable In-App.

Steps to reproduce:
1. Start purchase flow.
2. Press "Buy" button on Google Play dialog.
3. Quickly disable ALL connections on smartphone.
4. As result you will see, that product successfully bought, but consume isn't finished. 

Then, if you will try to bought the same product:

`org.solovyev.android.checkout.BillingException: An error occurred while performing billing request: ITEM_ALREADY_OWNED
        at org.solovyev.android.checkout.Request.onError(Request.java:147)
        at org.solovyev.android.checkout.Request.handleError(Request.java:172)
        at org.solovyev.android.checkout.Request.handleError(Request.java:167)
        at org.solovyev.android.checkout.PurchaseRequest.start(PurchaseRequest.java:61)
        at org.solovyev.android.checkout.Billing$OnConnectedServiceRunnable.run(Billing.java:829)
        at org.solovyev.android.checkout.PendingRequests.run(PendingRequests.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

Ok, but what about request with Inventory? Let's check:

`private class InventoryCallback implements Inventory.Callback {

        public InventoryCallback() {
        }

        @Override
        public void onLoaded(@Nonnull Inventory.Products products) {
            final Inventory.Product product = products.get(ProductTypes.IN_APP);
            if (!product.supported) {
                // billing is not supported, user can't purchase anything
                return;
            }

            purchaseMileage = product.getPurchaseInState(AppConstants.INAPP_OPEN_MILEAGE, Purchase.State.PURCHASED);

            if (purchaseMileage != null) {
                consume(purchaseMileage);
            }

        }
    }`

purchaseMileage is null and we can't consume this. As result, user can't buy this product. I've tried "adb shell pm clear com.android.vending" in terminal and restarting the device and clear Google Play data. Nothing can get it out of this state. I can fix thi only with new Gmail account or rename In-App. But this is not a solution. Mayb the problem not in this lib? Because: https://stackoverflow.com/questions/15542687/iabhelper-queryinventoryasync-returns-no-purchases-yet-launch-product-flow-fai

**Comment by thisisjatinrana** [comment]
Same problem. I made a purchase and consumed it when on purchase success but next time when in tried making purchase again it give me Item_already_owned error although inventory return empty purchase list.

**Comment by borosuman** [comment]
This may cause due to Base64 decoding failure. Return the public key in plain string format instead of encryption & check.
