### ISSUE TITLE
does this library check if the user got a refund?

### ISSUE THREAD

**Issue by photog0411** [serso/android-checkout#157]
i did a test purchase, went through successfully. I refunded the order in my play console. Now, 3 hours later, the app still thinks I own the purchased item. 

my implementation is pretty much exact to the guide.

**Comment by blood73** [comment]
Hi. Can you try to buy a refunded item in the app? Do you have ITEM_ALREADY_OWNED error?

**Comment by AntonioJoaquin** [comment]
Hi, I have the same problem. When I have refunded and it still like product purchased. Any solution? 
It is ok with suscriptions but my problem is with in_app type.

**Comment by AntonioJoaquin** [comment]
And yes, in my case when I try to buy a refunded item I have ITEM_ALREADY_OWNED error.

**Comment by ReckeDJ** [comment]
Hi all,

Have the same problem here. Just wondering, @AntonioJoaquin, was it fixed after some time? So that Google could process the refund? Or does the problem still exists?

Thanks!

**Comment by serso** [comment]
Hi guys, have you checked `Purchase#state` value?
