### ISSUE TITLE
How to make In-App purchase verifications

### ISSUE THREAD

**Issue by princeCoder** [serso/android-checkout#159]
Thanks for this awesome library.
Very to integrate but I have an issue regarding purchases verification. I honestly don't know what to do to verify that and I see I have to implement PurchaseVerifier interface. Can you please guide me through that?

Thanks

**Comment by binayakumar09** [comment]
Agreed. It would be great to know by some sample how do we validate if product is purchased. In the code, I have some adds. I want to have a check if the product is purchased or subscribed in the code and not show adds. Di I have to use google APIs? Is there some API that I can call to validate the same?
