### ISSUE TITLE
Base64DecodingException

### ISSUE THREAD

**Issue by thisisjatinrana** [serso/android-checkout#162]
Test purchase sku work good but getting this exception when trying to make real purchase. 
`org.solovyev.android.checkout.Base64DecodingException: Bad Base64 input character at 2: -66(decimal)`

Class DefaultPurchaseVerifier
line where exception occurs 
` if (Security.verifyPurchase(mPublicKey, purchase.data, purchase.signature))`

**Comment by serso** [comment]
It seems strange. I can't see such issue in my apps. Is it still repro?
