### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by imprakharshukla** [serso/android-checkout#165]
I am getting one error while using this library. This was discussed in a previous issue ( https://github.com/serso/android-checkout/issues/129 ) but the solution mentioned didn't worked for me.

Here are my files that I am getting the error on  https://gist.github.com/imprakharshukla/d98c174c24042ccb84c73e86a93a0e5f

The error 
**java.lang.NullPointerException: Attempt to invoke virtual method 'org.solovyev.android.checkout.Billing studio.com.techriz.andronix.BillingHelper.getBilling()' on a null object reference**  The logs are in the gist.

**Comment by serso** [comment]
Your `BillingHelper` is null. Not an issue in the library.

**Comment by imprakharshukla** [comment]
How can I solve this?
