### ISSUE TITLE
 Update to version 3  of Google Play Developer API

### ISSUE THREAD

**Issue by pzoleex** [serso/android-checkout#167]
Hi,

I've got this message: "We've detected that your is using an old version of the Google Play Developer API. From December 1 2019, version 1 and 2 of this API will no longer be available. Update to version 3 before this date. " in Google Play Developer Console.
 I'm using your lib org.solovyev.android:checkout:1.2.1.
 I don't use Google api anywhere else in my app. https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

Can you check it please?

**Comment by saulmaos** [comment]
Same here. Is there an email to contact developer? developer may need to check this too https://developer.android.com/google/play/billing/api

**Comment by Johnson145** [comment]
Where are you guys getting this message?

**Comment by saulmaos** [comment]
i'm using the latest version

**Comment by serso** [comment]
The reason why you are getting this message in Google Developer Console is that this library tries to recover transactions done via the old Billing API (v2). It's safe to ignore this message for now. I'll probably remove Billing API v2 references in the next release.

**Comment by serso** [comment]
The library has actually never used Billing API v2, my bad. You can check the commit for the explanation: 285c2943867036425215642eb2fc572c0402f5f0

**Comment by serso** [comment]
I've just published a new version of the library 1.2.2. It will be publicly available soon.
