### ISSUE TITLE
Why there is no support for acknowledged?

### ISSUE THREAD

**Issue by beshoo** [serso/android-checkout#168]
Hi
Recently android adds "acknowledged" method which you need to apply after the payment is done.
Otherwise, a refund will take place.

Please advice

**Comment by rpattabi** [comment]
I'm assuming, it is only relevant when using billing library client. If you know about this, please confirm.

Ref: https://stackoverflow.com/questions/56247438/google-play-billing-library-2-0-acknowledge-purchase-time-limit-for-test-purchas

**Comment by HonzaR** [comment]
Hi guys, speaking of that, which version of billing use this library? If version 3, as stated in readme page, shouldn't it use acknowledgement? Thank you.
