### ISSUE TITLE
Library not working always

### ISSUE THREAD

**Issue by eladgel** [serso/android-checkout#17]
I see a lot of reports in my logs about users(20% of users) that:
1. Do not get the product supported flag true
2. Do not get the inapp purchase items at all(product is supported)

for many other users all is working - how should I debug the lib to try and find where or why this err is happening

**Comment by serso** [comment]
eladgel, I noticed once that ServiceConnection#onServiceConnected was not called. I don't know if this happens often (I was unable to reproduce it anymore) but I prepared a fix. It is located in a [separate branch](https://github.com/serso/android-checkout/tree/reconnection), can you please try it and check if it was the cause of your issue? I prepared an archive if you don't want to build it yourself, you can find it [here](https://drive.google.com/file/d/0B2cXSv6b94RbUENlcFFPYnVwd0U/view?usp=sharing).

**Comment by eladgel** [comment]
I'll try it
Sorry for the late response

**Comment by serso** [comment]
I use the library in the project with 400k+ users and don't have any problems so far, please reopen the issue if you have more information.
