### ISSUE TITLE
Google Play Billing AIDL is deprecated

### ISSUE THREAD

**Issue by rpattabi** [serso/android-checkout#170]
As per android documentation, Google Play Billing AIDL is deprecated: https://developer.android.com/google/play/billing/api

> Warning: AIDL is now deprecated and will be removed in a future release. To implement Google Play Billing features, use the Google Play Billing library. 

I just want to bring this to @serso's notice to see if this impacts this library in any way. Or is this taken care of already or not relevant?

**Comment by serso** [comment]
Yes @rpattabi, I've already stumbled upon that when tried to get rid of "Old billing API" warning. Found a workaround for now. See https://github.com/serso/android-checkout/commit/285c2943867036425215642eb2fc572c0402f5f0 for more details.
