### ISSUE TITLE
Getting issue while upgrading subscription

### ISSUE THREAD

**Issue by arun1989** [serso/android-checkout#177]
Hello, 

I facing any issue while I am upgrading my subscription to monthly or yearly

 requests.changeSubscription(Collections.singletonList(activeSku),
                                newSku, null, checkout.getPurchaseFlow());

Error Message : 

![Screenshot_20210528-023424_Google Play Store](https://user-images.githubusercontent.com/12507057/119899538-35080780-bf11-11eb-9413-af9377797bb8.jpg)

**Comment by arun1989** [comment]
Is anyone here ?

**Comment by serso** [comment]
I tested updating subscriptions in the reference app and it works as expected. Not sure I can help you unless you provide more details.
