### ISSUE TITLE
ERROR: By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer.

### ISSUE THREAD

**Issue by Klug76** [serso/android-checkout#181]
Unfortunately, the project looks abandoned and is not compatible with the new Google Play requirements.
Now using ``com.android.billingclient.api.BillingClient`` instead of ``InAppBillingService`` is a mandatory.

**Comment by cupnoodle** [comment]
Try removing the billing permission in the .xml file, I suspect Google just check if this line exist and reject the release : 
https://stackoverflow.com/a/69936065

**Comment by cupnoodle** [comment]
I have just managed to solve it, aside from removing the billing permission in your android project manifest xml file, you also need to remove the billing permission line in this library module xml. You can download the .aar file, unzip it, remove that line from its android manifest.xml, then zip back it to .aar

**Comment by cupnoodle** [comment]
https://github.com/serso/android-checkout/blob/1ebd585926a5d97500b33b4c965c1b4ef4bb3c64/lib/src/main/AndroidManifest.xml#L28

**Comment by serso** [comment]
This issue is fixed in 1.2.4 release
