### ISSUE TITLE
The new version is not available (v1.2.4)

### ISSUE THREAD

**Issue by Husseinhj** [serso/android-checkout#183]
I tried to use the last version (1.2.4) but it's not available!

```
Failed to resolve: org.solovyev.android:checkout:1.2.4
```

Also checked the MVN repository and couldn't find the **AAR** file.

https://repo1.maven.org/maven2/org/solovyev/android/checkout/1.2.4/

**Comment by wgsoft-de** [comment]
I have the same problem.

**Comment by serso** [comment]
Not sure exactly what went wrong but I've published a new version 1.2.5 now.

**Comment by wgsoft-de** [comment]
Thanks, the version 1.2.5 works.
