### ISSUE TITLE
Do you plan to implement billing v5 ? 

### ISSUE THREAD

**Issue by wildfisher** [serso/android-checkout#188]
Thank you for your reply

**Comment by wildfisher** [comment]
I mean implementing the new functionality of Google Play subscriptions: several base plans per subscription, offers and so on.

**Comment by wgsoft-de** [comment]
I'm interested too. Unfortunately, it doesn't work with billing:5.1.0.

**Comment by serso** [comment]
Hey, sorry for not replying earlier. I don't plan working on the library any time soon. I suppose it's about time that I deprecate the library.
