### ISSUE TITLE
Problem loading the project in Android Studio

### ISSUE THREAD

**Issue by serso** [serso/android-checkout#26]
I've been trying opening your proj in Android Studio ("Open existing Android project") and encouraged some errors: http://i.imgur.com/xvMnSoJ.png

**Comment by serso** [comment]
Can you please try opening the project now?
The problem was in undefined properties in the project which I use for uploading the artifacts to the Maven repo. These properties are defined in my master gradle.properties file which is located in the home dictionary. Hopefully, changes in the latest commit fixes the issue for you.

**Comment by tral** [comment]
Hi, this problem is gone, now I have that one: http://i.imgur.com/ZIsEMXN.png

**Comment by serso** [comment]
Can you please set an ANDROID_HOME environment variable and check again?
The issue for it: https://github.com/serso/android-checkout/issues/27
