### ISSUE TITLE
DeadObjectException in GetPurchasesRequest.java:73

### ISSUE THREAD

**Issue by triveous** [serso/android-checkout#28]
Have seen this non-fatal exception on android 4.4 for multiple users, not sure if this is happening when making a purchase or periodically checking for purchases. Our app has a simple one time purchase item, would be happy to help with more information.

android.os.DeadObjectException
       at android.os.BinderProxy.transact(Binder.java)
       at com.android.vending.billing.IInAppBillingService$Stub$Proxy.a(IInAppBillingService.java:357)
       at org.a.a.a.bc.a(GetPurchasesRequest.java:73)
       at org.a.a.a.r.a(Billing.java:562)
       at org.a.a.a.bp.run(PendingRequests.java:155)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by serso** [comment]
I have never had such exception in the logs.
Do you forget to call org.solovyev.android.checkout.Checkout#stop from Activity#onDestroy?
Is your app open-source? Can you copy/paste code snippet of how you use the library?

**Comment by triveous** [comment]
The app is not open source, but can share a snippet of how we're using it. Here is a link to the gist: https://gist.github.com/triveous/295f1a75add2910c2379

In our onDestroy we do call the activityCheckout#stop method. Is that sufficient?

**Comment by triveous** [comment]
Is it a best practice to call Checkout#stop after checking for purchases or any other checkout operations, even if not called from an Activity?

**Comment by serso** [comment]
As [CheckoutActivity#start](https://gist.github.com/triveous/295f1a75add2910c2379#file-checkoutactivity-java-L26) might be called several times you need to call Checkout#stop() from it activityCheckout object is not null:
```
    private void start() {
        // stop if was started already
        stop();
        // clear our skus
        if (mSkus != null) {
            if (firstLoad) {
                InAppBilling.clearSkus();
                firstLoad = false;
            }
            InAppBilling.init(getApplicationContext(), mSkus);
            activityCheckout = Checkout.forActivity(this, InAppBilling.getCheckout(getApplicationContext()));
            activityCheckout.start();
        }
    }
```

**Comment by triveous** [comment]
Great, will do that, should I also call Checkout#stop() apart from the activityCheckout#Stop?

**Comment by serso** [comment]
Checkout#stop should be called when the work with Checkout is done. If you create a checkout object inside activity, both start() and stop() must be called inside it. If you create a checkout object in Application class you don't need to call stop() as it should live as long as application lives.

In your case is start() method is called with alive another Checkout object the old object will never be stopped.

I'm not sure if it *is* the cause of an exception but it *might be*.

No, you don't need (you can check the correctness by counting number of calls of start() and stop() methods: previously you had two calls of start and only one call of stop. Now you have two calls of start and two calls of stop)

**Comment by triveous** [comment]
thank you, i have implemented the same, will keep you posted on our findings.

**Comment by serso** [comment]
Please reopen if issue still shows up.
