### ISSUE TITLE
explain to me how to write 

### ISSUE THREAD

**Issue by Eldqs** [serso/android-checkout#32]
I want to add In Up Purchase to the application. Found the library earlier this did not, according to prescribed. Made, as in the example created Application, but more on examples it is not clear, explain to me, please.
what is PurchaseListener()? 
I created a content developer in the admin. Install dependencies, created a class application, copied from the example, but what to do next, how do I implement it, where to get the content ID, if you need it, and how do I display window shopping for only one content? Sat long with his example, but have not figured out, whether may it in one activity.
Please help me

**Comment by serso** [comment]
Hi, Have you looked into the [samples](https://github.com/serso/android-checkout/tree/master/app/src/main/java/org/solovyev/android/checkout/app)?

**Comment by Eldqs** [comment]
yes i loked this samples, but i don't understand how call checking and how call buying, you have writen list into fragment and it into activity, but how this list work i don't understand, i have one content that need check and to show payment windows. i tried understand two day but that don't understand, i created applicaiton class. 
please help me.

**Comment by Eldqs** [comment]
I'm sorry but I really do not understand how the whole process. Explain to me please

**Comment by Eldqs** [comment]
Вы кажется на русском понимаете, 
вот что я смог сделать, сделал по вашему примеру, хотел бы разобраться в вашем коде,
ничего не возвращется getcount = 0, 
        for (Inventory.Product product : inventory.getProducts()) {
            Log.i(tag, product.getPurchases() + " produ");
        }
выводит [] пусто,
посмотрите пожалуйста что я делаю не так.
https://github.com/Eldqs/inapppurchase/tree/master/app/src/main/java/kz/tanikin/inapppurchase2

**Comment by serso** [comment]
Напишите мне на почту: se.solovyev@gmail.com

**Comment by VladimirUA** [comment]
у меня тоже, строка 

```Java
private class InventoryLoadedListener implements Inventory.Listener {
        @Override
        public void onLoaded(@NonNull Inventory.Products products) {
            final Inventory.Product product = products.get(IN_APP);

            if (product.supported) {
                for (Sku sku : product.getSkus()) {
                    final Purchase purchase = product.getPurchaseInState(sku, Purchase.State.PURCHASED); //всегда возвращает null 
                    showSubscriptionInfo(sku, product);
```

**Comment by druidamix** [comment]
I agree the documentation is bad

**Comment by serso** [comment]
To get list of SKUs you have to provide list of SKU ids in the constructor of Products, f.e.:
```java
@Nonnull
private final Checkout checkout = Checkout.forApplication(billing, Products.create().add(IN_APP, asList("product")));
```
Note that "product" is a SKU id here. As this information can be found both in README to the project and in the sample application I can't agree that documentation is poor in this particular case.
