### ISSUE TITLE
SKUs not loaded

### ISSUE THREAD

**Issue by wojciiii** [serso/android-checkout#36]
I have an issue with using the library. 
After calling Checkout.loadInventory() I expect the following to get the SKUs for a product, but the list is empty. How do I get the SKUs for a product? This is not something covered in documentation and the comments state that it is uncertain if the SKUs are present.

Inventory.Products products = mInventory.getProducts();
for (Inventory.Product p: products)
{
    List<Sku> skus = p.getSkus();
    Log.d(TAG, "skus: " + skus.size());
    for (Sku s: skus)
    {
        JSonSkus.add(Helper.toJson(s));
    }
}

**Comment by serso** [comment]
Hi, have you looked in the source code of [the sample app](https://github.com/serso/android-checkout/tree/master/app/src/main/java/org/solovyev/android/checkout/app)?

The main thing you should check is that you provide a full list of SKUs while creating a checkout object, f.e.: 
```java
final Checkout checkout = Checkout.forApplication(billing, Products.create().add(IN_APP, asList("coffee", "beer", "cake", "hamburger")));
```
As information about SKU can be loaded only by its id we have to provide a list of ids before creating the Inventory.

**Comment by serso** [comment]
Closing the issue. If you still have problems don't hesitate to reopen it.

**Comment by wojciiii** [comment]
Thanks for your reply. I had issues with understanding the documentation and this issue was caused by me not understanding some of the options. I was using a wrong input string for creating a product.
