### ISSUE TITLE
getPurchaseVerifier and isAutoConnect not mentioned in examples anywhere?

### ISSUE THREAD

**Issue by xbroak** [serso/android-checkout#39]
It seems when implementing that Billing.Configuration now requires these two methods,

by default they return null and false respectively, neither the example app nor the read me shows any mention of these two functions and i'm not sure what they do nor what i am supposed to put in them?

**Comment by serso** [comment]
You always can extend Billing.DefaultConfiguration class to use default implementation for these methods. And check out javadocs for Billing.Configuration - reading it should be enough to understand what values to return. More details about purchase verification you can find [here](https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/PurchaseVerifier.java)
