### ISSUE TITLE
Inventory.load().whenLoaded(listener) does not callback if google account has been deleted

### ISSUE THREAD

**Issue by Alviere** [serso/android-checkout#42]
So here's the situation:
When user don't have an google account, whenLoaded calls listener fine, but Invetory.Product is not supported.
When user adds google account (assuming that he didn't destroy app instance) and try to buy again, everything works just fine.
But if after Inventory.load() with google account on device user deletes his account, Inventory.load().whenLoaded() didn't call listener and app stays still.

Please, look into this issue.

**Comment by serso** [comment]
It looks like a very theoretical use-case. Why would anyone remove Google account from the phone?
