### ISSUE TITLE
Loading Inventory whenLoaded listener callback

### ISSUE THREAD

**Issue by markfili** [serso/android-checkout#53]
Hi, I've noticed that the method in BaseInventory.whenLoaded(Listener listener) only adds the listener once we call it, even though the Inventory is loaded (it appears so when debugging). 
When would it be timely appropriate to call the whenLoaded() method to get the correct response and state of the inventory (isLoaded())?
For now, if I put it in a Handler with delay, it works, but without this, it only adds the listener and never calls it.

**Comment by serso** [comment]
No, Listener#onLoaded is called right away if the inventory object is already loaded, see [BaseInventory#whenLoaded](https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/BaseInventory.java#L69)

**Comment by markfili** [comment]
True, if it's already loaded, but what about when it's yet to be loaded? 
Shouldn't that trigger the callback? 
I saw that a Counter is responsible for the status of the loading, but BaseInventory#whenLoaded calls Counter#isFinished() some time before the counter has finished counting so it returns false and adds a listener.
It seems to me that it doesn't wait for loading to finish or it cannot know for sure when the loading has ended. 
Sorry to bother you, I admire your work and thank you for your effort.
