### ISSUE TITLE
get purchases from inventory local after reboot and no internet connection   

### ISSUE THREAD

**Issue by tamtom** [serso/android-checkout#54]
if the user purchase an item then the inventory should save this right ? but after a reboot and no connection to internet the item is not owned , the user should connect to internet to restore the purchase , which is annoying , is there a solution for this ? I thought of saving the purchase in shared preference which is not secure

**Comment by serso** [comment]
The documentation of Billing API v.3 claims that local caching is used there [1]. Thus, persistent client caching is redundant and was not included in the library.
However, if you really want to save purchases on disk you can do it with the help of `org.solovyev.android.checkout.Cache`. Just implement your version and provide it in `org.solovyev.android.checkout.Billing.Configuration#getCache`.

[1]: https://developer.android.com/google/play/billing/api.html#caching
