### ISSUE TITLE
Problems checking in app purchase after reboot (updated play service < 9 to 9.4)

### ISSUE THREAD

**Issue by MFlisar** [serso/android-checkout#55]
I recently got a few error reports of people telling me, that after a reboot my app is reporting it is the free version instead of the pro version... They have to enable internet connection and then after a short time it works.

The only change I made recently is that I updated from play services 8.7 to 9.4 and my support libraries from v23 to v24... Nothing more. Not sure if this is in any way related though...

**My app is live for years, never had one single issue before!**

Anyone having this problem too? Is this normal? I thought, the play store is caching the purchases and is repsonding with old cached results if no internet connection exists. Until now, I only got reports reporting about this issue after a reboot (not after turning off the internet or so), but after a reboot if they have no internet connection after the reboot....

**Comment by nicolausYes** [comment]
#54

**Comment by serso** [comment]
The documentation of Billing API v.3 claims that local caching is used there [1](https://developer.android.com/google/play/billing/api.html#caching). Thus, persistent client caching is redundant and was not included in the library.
However, if you really want to save purchases on disk you can do it with the help of org.solovyev.android.checkout.Cache. Just implement your version and provide it in org.solovyev.android.checkout.Billing.Configuration#getCache.
