### ISSUE TITLE
getBilling or getCheckout?

### ISSUE THREAD

**Issue by Daemon55** [serso/android-checkout#59]
Сергей,

Пробую вашу библиотеку в проекте.
Возник вопрос, в readme и в примере используется getBilling, но при подключении через gradle forActivity требует второй параметр в виде Checkout. 
Есть какая-то разница в библиотеке и последних исходниках?
--
С уважением, Дмитрий

**Comment by serso** [comment]
Да, разница есть. Я работаю над новой версией, в которой немного изменился API. Ожидайте обновления в скором времени.
А пока вы можете использовать старую документацию: https://github.com/serso/android-checkout/blob/535f94cc56e289a23526047cea40cfae5975d870/README.md
