### ISSUE TITLE
Working with test purchases?

### ISSUE THREAD

**Issue by sipersso** [serso/android-checkout#60]
How do I test my app if I use Checkout? 

The billing request always seem to add my package name, which will work fine in production, but not when testing with static responses. If I try to purchase "android.test.purchased" the request it will send out "sp.repcount" as package name and "android.test.purchased" as SKU. Or am I missing something?

**Comment by serso** [comment]
No, this looks good. What exactly doesn't work in your case? Do you get an error? What is the error code?

**Comment by sipersso** [comment]
Static responses and subscriptions doesn't seem to mix well. I wasn't aware of this. The Google in app purchase apis leaves a lot to be desired in terms of testing. Nothing wrong with Checkout after all. Thank you for an awesome library and fast response!
