### ISSUE TITLE
Implement Billing v6: getBuyIntentExtraParams

### ISSUE THREAD

**Issue by serso** [serso/android-checkout#63]
See https://developer.android.com/google/play/billing/billing_reference.html

**Comment by peterhav** [comment]
Hi @serso, are there any plans on implementing this in the library? I have the need to supply subscription updates/downgrades to my users. Where would this impact the existing library?

**Comment by serso** [comment]
@peterhav you can already use #getBuyIntentToReplaceSkus. See "Use case #4. Managing subscriptions" [here](https://hackernoon.com/implementing-in-app-billing-in-android-4896232c7d6b#.3te2ae61b).

Regarding the mentioned API method: as described in #65 the AIDL file was not updated by Google => it was not possible to implement it. It might be fixed now, I'll probably take a look at the weekend

**Comment by serso** [comment]
Reopen when Billing v.6 is released

**Comment by serso** [comment]
It seems that the AIDL file is now updated and the support for v6 can be implemented: https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl
