### ISSUE TITLE
SKUs not loading

### ISSUE THREAD

**Issue by Querschlag** [serso/android-checkout#66]
I followed the sample code to fetch available SKUs, but I don't get any results.
Is this the correct way of retrieving SKUs or am I missing something?
Do I need to include AIDL?
```
checkout = Checkout.forActivity(this, (application as MyApplication).billing)
checkout.start()

inventory = checkout.makeInventory()
inventory?.load(Inventory.Request.create()
        .loadAllPurchases()
        .loadSkus(IN_APP, "product_id-01")
        .loadSkus(SUBSCRIPTION, "product_id-02"),
        {
            val skus: MutableList<Sku> = mutableListOf()
            val subs = it[SUBSCRIPTION].skus
            val inapp = it[IN_APP].skus
            skus.addAll(subs)
            skus.addAll(inapp)
            // skus.count() is 0
            menu.reload(skus)
        })
```

**Comment by serso** [comment]
What language is this? Kotlin? :P

The code looks right so I suggest checking the application logs. Have you uploaded the app to Google Play? Billing API doesn't work unless the app is published: https://developer.android.com/google/play/billing/billing_testing.html

**Comment by Querschlag** [comment]
Yes, Kotlin <3
So, 2 problems on my side. Used a different applicationId and didn't upload to Google Play.
Now it's working like a charm. Thanks.
