### ISSUE TITLE
Build Fails With Proguard

### ISSUE THREAD

**Issue by ghost** [serso/android-checkout#67]
It seems like proguard fails release builds due to missing javax annotations.
Example error:
`Warning:org.solovyev.android.checkout.ActivityCheckout: can't find referenced class javax.annotation.Nonnull`

Tried:
* Explictly adding the library's `proguard-rules.pro` to the app's
* Adding the javax annotations package to gradle (`provided "org.glassfish:javax.annotation:10.0-b28"`) - **didn't work**, proguard still fails the build (even if I compile the annotations rather than simply using `provided`)
    * It's worth mentioning I've tried this with all 3 popular javax annotation packages.
* Adding `-dontwarn javax.annotation.**` - **worked**, but it's rather hacky.

Any hints on this issue? Should I just open a Pull Request fixing the proguard rules for the library?

**Comment by serso** [comment]
How do you import the library to your project? Do you use Gradle?

If you don't use Gradle you should add 'com.google.code.findbugs:jsr305:2.0.3' dependency manually, see [build.gradle](https://github.com/serso/android-checkout/blob/master/lib/build.gradle#L44). The jars can be found, for example, [here](https://bintray.com/bintray/jcenter/com.google.code.findbugs%3Ajsr305)

**Comment by eran1243** [comment]
I do use gradle.

**Comment by serso** [comment]
@eran1243, have you resolved the issue? Have you checked Gradle logs? You can try adding `com.google.code.findbugs:jsr305:2.0.3` to your dependency list:
dependencies {
  compile('com.google.code.findbugs:jsr305:2.0.3')
}

**Comment by serso** [comment]
Please reopen the issue of the problem persists.

**Comment by peterhav** [comment]
Just encountered the same issue: adding only the `compile 'org.solovyev.android:checkout:0.9.2@aar' is not enough (it will give proguard issues). Adding also `compile('com.google.code.findbugs:jsr305:2.0.1')` to the build dependencies solves the problem.

**Comment by peterhav** [comment]
Note: adding these lines to the proguard configuration might be a better solution (compared to adding the JSR dependency):

```
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.Nonnull
-dontwarn javax.annotation.concurrent.GuardedBy
-dontwarn javax.annotation.concurrent.ThreadSafe
-dontwarn javax.annotation.concurrent.Immutable
```

**Comment by serso** [comment]
You can also set `transitiv`e to `true` in the dependency definition in your `build.gradle`:
```
compile ('org.solovyev.android:checkout:0.9.3@aar') {
  transitive = true
}
```

I'll update the documentation and close this issue
