### ISSUE TITLE
Getting active purchases

### ISSUE THREAD

**Issue by gitars** [serso/android-checkout#71]
Hey, thanks for all your work on this library, it is very helpful. I was just having an issue that hopefully you can help me with. 

When I try to load the current purchases that the user has in their inventory, it always shows up as empty. (I know this is wrong because when I load the purchases using the native code I had before starting to use your library, it shows the purchase. Also, when I try to buy a purchase the specific item, gives me back the error `ITEM_ALREADY_OWNED`). Also, I do not have any problems loading SKUs available for purchase.

Below is the code that I use to get the user's inventory, does there seem to be anything obviously wrong here to you? (The item is a managed product, not a subscription).

```
public static void loadInAppPurchaseSku(@NonNull final Checkout checkout, @NonNull final List<String> productSkus, @NonNull final List<String> subscriptionSkus) {
    checkout.loadInventory(Inventory.Request.create()
            .loadAllPurchases()
            .loadSkus(ProductTypes.IN_APP, productSkus)
            .loadSkus(ProductTypes.SUBSCRIPTION, subscriptionSkus), new Inventory.Callback() {
        @Override
        public void onLoaded(@Nonnull final Inventory.Products inventoryProducts) {
            Inventory.Product products = inventoryProducts.get(ProductTypes.IN_APP);
            final List<Purchase> purchases = products.getPurchases();
            Log.e("XXXX", "found " + purchases.size() + " purchases"); // always says found 0 purchases
            // The item I'm concerned with does, however, show up in products.getSkus()
        }
    });
}
```

**Comment by gitars** [comment]
@serso any ideas? The apk in question has been in alpha on google play for 3 days now, so I'm confident it's not an issue related to that.

**Comment by serso** [comment]
Have you seen https://github.com/serso/android-checkout/blob/master/lib/src/main/java/org/solovyev/android/checkout/BasePurchaseVerifier.java? If you subclass it you should be able to do a heavy verification procedure on a background thread.

**Comment by serso** [comment]
If you want to use another thread for doing network requests you should wait the result on the thread which is used in the Billing request. As it's not the main application thread it's okay to halt it.

**Comment by gitars** [comment]
Ahh. I missed that this was on thread. Thanks!
