### ISSUE TITLE
Carsh IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by aminelaadhari** [serso/android-checkout#72]
There is a crash with library version 0.9.2. Here the details:

If the billing class has no PlayStoreListener added, when the activity is destroyed PlayStoreBroadcastReceiver.removeListener calls unregisterReceiver which cause the crash.

**Comment by spacedema** [comment]
Have the same errors

**Comment by serso** [comment]
The fix is available in 0.9.3. Please update the library version

**Comment by spacedema** [comment]
Thanks!
