### ISSUE TITLE
GetPurchasesRequest doesn't work with an asynchronous PurchaseVerifier

### ISSUE THREAD

**Issue by castelanjr** [serso/android-checkout#76]
First of all: thanks for your hard work on this awesome library.

This is the problem I'm facing: I have a custom `PurchaseVerifier` that extends `BasePurchaseVerifier` and does all the logic in a remote server, which means it takes a few milliseconds before the callbacks are called. Problem is, `GetPurchasesRequest` expects an immediate call to `onSuccess()` or `onError()`, which causes the request to fail and not show any purchases. 

You can check on `GetPurchasesRequest`, line 89:
```
mVerifier.verify(purchases, listener);
if (!listener.mCalled) {
    listener.onError(ResponseCodes.EXCEPTION, new IllegalStateException("Either onSuccess or onError methods must be called by PurchaseVerifier"));
}
```

My suggestion is to get rid of `mCalled` in the `VerificationListener`, because it breaks the functionality I described. Also, it's the client's responsibility to call the listener correctly. 

I can send you a pull request doing this, but I wanted to check with you first if there aren't going to be any side effects or something.

Thanks!

**Comment by serso** [comment]
The idea is that `BasePurchaseVerifier#doVerify` can be blocked if a long computation is required.
If you do a network request you can do it directly on the thread on which `doVerify` is called.
If you use a library that spawns a new thread for sending a request then you can block execution of the current thread until the request is finished (CountDownLatch or Future classes can help you to achieve this).

If something is unclear please don't hesitate to ask.

**Comment by castelanjr** [comment]
Yeah, I turned my network request into a blocking operation, it's working great now. Guess I should have read the source code for `BasePurchaseVerifier` before asking hahah.

Thanks for your help!
