### ISSUE TITLE
error while performing gradle sync

### ISSUE THREAD

**Issue by lumleon** [serso/android-checkout#77]
Error:Could not find com.android.support:support-v4:23.4.0.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
    file:/null/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
    file:/null/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
    https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.pom
    https://repo1.maven.org/maven2/com/android/support/support-v4/23.4.0/support-v4-23.4.0.jar
Required by:
    android-checkout-master:app:unspecified

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by serso** [comment]
Please install the Android Support Repository from the Android SDK Manager.
Open Android SDK Manager

**Comment by lumleon** [comment]
the repository 25.1.1 was installed and work fine in other project but  same issue appeared  in this clone.

**Comment by serso** [comment]
Historically, `ANDROID_HOME` was used to get hold of the local maven repository. It seems that now `mavenLocal()` can be used for this instead. I'll fix the build script
