### ISSUE TITLE
Sample application null point

### ISSUE THREAD

**Issue by avipars** [serso/android-checkout#82]
I'm trying to open the banner activity from my MainActivity, but am getting this error: 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

**Comment by avipars** [comment]
The error occurs on this line:          mAd.setOnClickListener(this);

and this is the code to start the intent:                startActivity(new Intent(MainActivity.this,  BannerActivity.class));

**Comment by serso** [comment]
How do you build the project? Butterknife should generate some view bindings and it's done automatically if you build the project with Gradle.

**Comment by serso** [comment]
Can't repro, more info needed

**Comment by avipars** [comment]
I think I was on the wrong ButterKnife version, sorry.
