### ISSUE TITLE
E/Billing/Security: Base64 decoding failed.

### ISSUE THREAD

**Issue by AlexioVay** [serso/android-checkout#84]
Hello,

my app is in closed alpha stage for testing and I just made a test purchase on an item, but the @onError method was called. I immediately got the "Google Play Order Receipt" via email that seems to be successful. 
However, the log says "03-28 16:15:33.636 18541-18541/? E/Billing/Security: Base64 decoding failed." and I checked my API and pasted the correct key (used your app code for encryption to test it). Even completely without encryption and just returning the plain API key I get this error message in the log.

But is this really an error or is this just produced because it's an test purchase? It's really annoying to test inapp purchases since I always have to upload the signed .apk file and wait 1-2 hours just for testing little steps like this.
Is there a method or some other way without the need of uploading the apk to confirm my API key verification is successful and avoid this error? 
Or am I missing some steps to avoid this error?

Thank you in advance.

**Comment by serso** [comment]
@AlexioVay if you receive a signature from Google Play it should be correct. `org.solovyev.android.checkout.Security` class verifies that the base-64 encoded developer public key is the same as the signature passed with a purchase. This is needed to prevent fake market apps (or MITM) of sending fake data to your app.
Things to check:
1. You use your developer public key in the app
2. It's base-64 encoded
3. Debug `org.solovyev.android.checkout.Security` and check what exactly is wrong there.

Please let me know if it still doesn't work.

**Comment by Astralgr** [comment]
@serso I get the exact same problem from above.
I use our CheckoutApplication.java with my License key from the developer console.

When I have

> return  Encryption.decrypt(s, MAIL);

  I get "E/Billing/Security: Base64 decoding failed" error.

When I only have

> return  s;

Purchase is fine and AdBanner dissapears.

As you said in an other post, it's not secure, so could you please help me fix the Problem ?

**Comment by serso** [comment]
@Astralgr https://developer.android.com/google/play/billing/billing_best_practices.html#validating-purchase-device:
> You should obfuscate your Google Play public key and In-app Billing code so it's difficult for an attacker to reverse-engineer security protocols and other application components
You should choose some two-way encryption algorithm. Encrypt your PK, put it somewhere in the code. When it's used you should decrypt it.

**Comment by Pozinux** [comment]
Hi, same problem as @Astralgr here. When I don't decrypt and only return "s", it is working fine. Otherwise I get the famous "E/Billing/Security: Base64 decoding failed" error.

**Comment by serso** [comment]
The string should be encrypted first and only the result should be left in the code.
Here, for example, `s` is an encrypted public key which I got via calling Security.encrypt(PK) before hand (PK=public key): 
https://github.com/serso/android-checkout/blob/77b54014f803f3394384d2cbc194b21d2bd22472/app/src/main/java/org/solovyev/android/checkout/app/CheckoutApplication.java#L23

**Comment by Pozinux** [comment]
Thanks! Works perfectly well now!
