### ISSUE TITLE
After uninstalling and installing application again, first time opening the application Inventory.Callback::onLoaded doesn't return the purchased items 

### ISSUE THREAD

**Issue by asimugrabi** [serso/android-checkout#86]
Hi,
First of all thank you for sharing your library.

I noticed the following issue: 
After uninstalling the application and installing it again, only for the first time opening the application, onLoaded does not return the purchased items. 
From second time and on after reopening the app, the purchased items are loaded correctly. 
As a side note: If I put a debug point at onLoaded the purchased items get updated correctly. So it seems there is a race condition somewhere along the way.

This is the code I use:

```
protected void onCreate(Bundle savedInstanceState) {
 .........
    mCheckout = Checkout.forActivity(this, new Billing(this, new Billing.DefaultConfiguration() {
            @Nonnull
            @Override
            public String getPublicKey() {
                return "not_used";
            }

            @Nonnull
            @Override
            public PurchaseVerifier getPurchaseVerifier() {
                return new YankaPurchaseVerifier(CalendarActivity.this);
            }
        }));
        mCheckout.start();
        Inventory inventory = mCheckout.makeInventory();
        inventory.load(Inventory.Request.create()
                .loadPurchases(ProductTypes.IN_APP)
                .loadSkus(ProductTypes.IN_APP, SKU_PREMIUM), new InventoryCallback());
.....
```

```
    private class InventoryCallback implements Inventory.Callback {

        @Override
        public void onLoaded(@Nonnull Inventory.Products products) {
            for (Inventory.Product product : products) {
                if (product.isPurchased(SKU_PREMIUM)) {
                    mIsPremium = true;
                }
            }
            mDrawerLayout.setVisibility(View.VISIBLE);
        }
    }
```

Thanks!

Edit: For the first time PurchaseVerifier is also not called.

**Comment by serso** [comment]
I cannot reproduce the issue in the sample app ([Store](https://play.google.com/store/apps/details?id=org.solovyev.android.checkout.app), [source code](https://github.com/serso/android-checkout/tree/master/app/src/main)). If I uninstall it and install again the purchases are restored on the first application start.

If the purchase verifier is not called that means that Checkout hasn't received any purchases from the billing API.

Can you reproduce the issue every time you clean the app's data?

**Comment by asimugrabi** [comment]
serso thank you for replying.

I tested this some more and here is what what i found.
1. I can reproduce this issue every time if I uninstall and install from Android Studio
2. If I clear data and open the app, works good.
3. If I uninstall and install via Google Play, then it also works good.
4. If I change to android:allowBackup="false", then it works good when installing via Android Studio

i can't wrap my head around what may cause it for Android Studio. Any ideas? 
Since it works as intended when installing from Google Play, I think you can close this as it doesn't seem like a real issue.

Thanks

**Comment by serso** [comment]
Do you use "Instant Run" feature? Try disabling it and see what happens.

**Comment by asimugrabi** [comment]
I was not using Instant Run.
