### ISSUE TITLE
product.getPurchases() return empty list

### ISSUE THREAD

**Issue by invizorys** [serso/android-checkout#89]
I have already made 2 subscriptions but **product.getPurchases();** return empty list.
What am I doing wrong?
```
mCheckout.loadInventory(request, new Inventory.Callback() {
    @Override
    public void onLoaded(@Nonnull Inventory.Products products) {
	final Inventory.Product product = products.get(SUBSCRIPTION);
        List<Purchase> purchases = product.getPurchases();
    }
});
```

**Comment by serso** [comment]
Is it production version? Have you checked logs? Most common reason is that the subscriptions can't be verified, check `PurchaseVerifier` class.

**Comment by invizorys** [comment]
Yes, it's production version(app published in alpha channel). I have such line in logs:
`E/Billing/Security: Signature verification failed.`

`PurchaseVerifier` require `List<Purchase> purchases` as a parametr, how I can receive this list?

**Comment by serso** [comment]
Have you read the documentation? You can set your own implementation of `PurchaseVerifier` via `Billing.Configuration#getPurchaseVerifier`

**Comment by invizorys** [comment]
Yes, I have read. But I still don't understand how I can receive purchase for verification.

**Comment by invizorys** [comment]
I have such message:
`Cannot verify purchase: Purchase{state=PURCHASED, time=1493327642358, sku='test_sku_1'}. Wrong signature`

**Comment by invizorys** [comment]
I have such line in logs:
`Cannot verify purchase: Purchase{state=PURCHASED, time=1493328825321, sku='subscription_one_month'}. Wrong signature`
What could be the problem?

**Comment by invizorys** [comment]
Yes, I have read. But why is `DefaultPurchaseVerifier` not working for me?

**Comment by serso** [comment]
`DefaultPurchaseVerifier` should work out-of-the-box in release builds. The log statement says that the signature is corrupt. It might be that the public key you use is not properly encoded or just wrong. Take a look at `org.solovyev.android.checkout.Billing.Configuration#getPublicKey`

**Comment by invizorys** [comment]
I use `DefaultConfiguration` with [public key from example app](https://github.com/serso/android-checkout/blob/master/app/src/main/java/org/solovyev/android/checkout/app/CheckoutApplication.java#L18)

**Comment by serso** [comment]
You should use your own public key

**Comment by invizorys** [comment]
The problem was that I forgot to replace the public key.
Thank you very much for your help.

**Comment by serso** [comment]
@invizorys :+1:
