### ISSUE TITLE
Check subscribtion in the application class

### ISSUE THREAD

**Issue by psohm** [serso/android-checkout#91]
Is it possible (and advised) to make the check of the subscribtion status in the application class ?
I need an ActivityCheckout (I think so) in the activity.
so I think I have to create a second Checkout object only for the application.
Is it correct and can it cause some problems ?

Regards

**Comment by serso** [comment]
It's okay to create several Checkout objects, see for example the samples app.
Don't forget to destroy them properly in `Activity#onDestroy()`.
