### ISSUE TITLE
Check if product has been bought

### ISSUE THREAD

**Issue by oksett** [serso/android-checkout#97]
Is there a way to check if product is bought? I tried do this onLoaded Callback:
@override
public void onLoaded(Inventory.Products products) {
// Inventory.Product product = products.get(MY_PRODUCT_ID);\

But i get this Exception:

06-16 12:00:12.747 32539-32539/com.coderspeak.smog_app E/AndroidRuntime: FATAL EXCEPTION: main Process: com.coderspeak.smog_app, PID: 32539 org.solovyev.android.checkout.Check$AssertionException: Unsupported product: com.coderspeak.smogapp.bronzemedal at org.solovyev.android.checkout.Check.isTrue(Check.java:98) at org.solovyev.android.checkout.ProductTypes.checkSupported(ProductTypes.java:54) at org.solovyev.android.checkout.Inventory$Products.get(Inventory.java:124) at com.coderspeak.smog_app.activity.InAppBillingActivity$InventoryCallback.onLoaded(InAppBillingActivity.java:124) at org.solovyev.android.checkout.BaseInventory$Task.onDone(BaseInventory.java:166) at org.solovyev.android.checkout.BaseInventory$Task.onDone(BaseInventory.java:145) at org.solovyev.android.checkout.CheckoutInventory$Worker.countDown(CheckoutInventory.java:92) at org.solovyev.android.checkout.CheckoutInventory$Worker.countDown(CheckoutInventory.java:84) at org.solovyev.android.checkout.CheckoutInventory$Worker.access$000(CheckoutInventory.java:35) at org.solovyev.android.checkout.CheckoutInventory$Worker$1.onSuccess(CheckoutInventory.java:102) at org.solovyev.android.checkout.CheckoutInventory$Worker$1.onSuccess(CheckoutInventory.java:98) at org.solovyev.android.checkout.BaseInventory$SynchronizedRequestListener.onSuccess(BaseInventory.java:193) at org.solovyev.android.checkout.Billing$Requests$GetAllPurchasesListener.onSuccess(Billing.java:1151) at org.solovyev.android.checkout.Billing$Requests$GetAllPurchasesListener.onSuccess(Billing.java:1134) at org.solovyev.android.checkout.MainThreadRequestListener$1.run(MainThreadRequestListener.java:55) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6682) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by threat70** [comment]
At first you should select product type `products.get(ProductTypes.IN_APP)` and then check state of your product like this `products.get(ProductTypes.IN_APP).isPurchased(PRODUCT_ID)`

Correct me if I'm wrong

**Comment by rpattabi** [comment]
That's right. In the API, at times the word `Product` is used to mean `Product Type` (IN_APP/SUBSCRIPTION) which may be the reason for your confusion.

`products.get(ProductTypes.IN_APP).isPurchased(SKU)` is correct.

**Comment by serso** [comment]
@threat70 and @rpattabi are correct. I decided to use "product" name in the library for product types as Android Billing uses "productId" (see for example [this page](https://developer.android.com/google/play/billing/billing_reference.html)). The actual items are identified by their SKUs and the variables are usually named "skuId" for identifiers and "sku" if it's Sku object
