### ISSUE TITLE
How to supply the user id for which a purchase query / request must be placed?

### ISSUE THREAD

**Issue by jagan999** [serso/android-checkout#99]
Hello,

I find your library easy to use. However, one area I am stuck is how to supply google userid for which we need to query the purchases done or make a purchase. Please advice me how to do this. My app currently allows the user to select a google account to be used. However if I use your library, it seems to take the currently logged in user profile on the device, not the account the user selected.

**Comment by serso** [comment]
Billing API doesn't know about users and doesn't provide any API to choose a specific user account in the system. Please refer to https://stackoverflow.com/questions/15263889/does-in-app-billing-support-multiple-accounts and https://issuetracker.google.com/issues/36967788
